import type { Metadata } from "next";
import Link from "next/link";
import { ButtonLink } from "@/components/button-link";
import { JsonLd } from "@/components/json-ld";
import { siteConfig } from "@/config/site";
import { organisationSchema, websiteSchema } from "@/lib/structured-data";

export const metadata: Metadata = { title: "Bestone Services Ltd | Cleaning & Pest Control", description: "End of tenancy cleaning and pest-control services across London. Explore active services, starting prices and coverage information.", alternates: { canonical: "/" } };
const process = [["Choose a service", "Start with end of tenancy cleaning or pest control."], ["Share the useful details", "Use email to explain the property, service area and timing."], ["Confirm the next step", "Scope, availability and final price are confirmed before booking."]] as const;
export default function HomePage() { return <main id="main-content"><JsonLd data={{ "@context": "https://schema.org", "@graph": [organisationSchema(), websiteSchema()] }} />
  <section className="shell hero"><div className="hero-copy"><p className="eyebrow">London property services</p><h1>End of tenancy cleaning and pest control, clearly arranged.</h1><p className="lead">Explore active services, see approved starting prices and contact Bestone Services Ltd with the property details that matter.</p><div className="button-row"><ButtonLink href="/contact/">Contact Us</ButtonLink><ButtonLink href="/cleaning-services/end-of-tenancy-cleaning/" secondary>Explore Cleaning</ButtonLink></div></div><div className="quick-answer"><p className="eyebrow">Two core services</p><h2>One practical starting point.</h2><p>For rental properties, homes and businesses across London, subject to operational availability.</p></div></section>
  <section className="section section-white"><div className="shell service-grid"><article className="service-card"><div><p className="eyebrow">Cleaning</p><h2>End of tenancy cleaning</h2><p>Property-focused cleaning support for tenants, landlords, letting agents and property managers.</p><ButtonLink href="/cleaning-services/end-of-tenancy-cleaning/">View Cleaning</ButtonLink></div></article><article className="service-card"><div><p className="eyebrow">Pest control</p><h2>Pest control services</h2><p>Explore common pest-control treatments and contact the team with the relevant property details.</p><ButtonLink href="/pest-control-services/">View Pest Control</ButtonLink></div></article></div></section>
  <section className="section" id="how-it-works"><div className="shell"><div className="section-head"><div><p className="eyebrow">How it works</p><h2>From service details to a confirmed next step.</h2></div></div><div className="process-grid">{process.map(([title, text]) => <article className="process-card" key={title}><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
  <section className="section section-white"><div className="shell quote-band"><div><p className="eyebrow">Useful information</p><h2>Prices, areas and service guidance.</h2><p>Starting prices are clear about their limits. Area coverage is confirmed for each request.</p></div><div className="button-row"><ButtonLink href="/prices/" secondary>Prices</ButtonLink><ButtonLink href="/areas/" secondary>Areas</ButtonLink><ButtonLink href="/guides/" secondary>Guides</ButtonLink></div></div></section>
  <section className="section section-alt"><div className="shell"><div className="faq-heading"><p className="eyebrow">Explore services</p><h2>Find the right route.</h2></div><div className="card-grid"><article className="content-card"><h3>About Bestone Services Ltd</h3><p>Company details, service approach and public standards.</p><Link href="/about/">About us</Link></article><article className="content-card"><h3>Contact</h3><p>Email the team with a service requirement and property information.</p><Link href="/contact/">Contact us</Link></article><article className="content-card"><h3>Booking</h3><p>The secure guest booking journey is planned for the M2 milestone.</p><Link href="/booking/">Booking information</Link></article></div></div></section>
</main>; }
