import { serviceFaqSchema, type ServiceFaq } from "@/content/service-types";

type ApprovedServicePage = {
  title: string;
  description: string;
  summary: string;
  signsTitle: string;
  signs: readonly string[];
  process: readonly [string, string][];
  price: string;
  priceFactors: readonly string[];
  prevention: readonly string[];
  faqs: readonly ServiceFaq[];
};

const page = (data: Omit<ApprovedServicePage, "faqs"> & { faqs: readonly { question: string; answer: string }[] }) => ({ ...data, faqs: serviceFaqSchema.array().parse(data.faqs) });

export const approvedServicePages = {
  "cleaning-services/end-of-tenancy-cleaning": page({
    title: "End of Tenancy Cleaning",
    description: "End of tenancy cleaning in London for tenants, landlords and letting agents. Starting from £79; final scope and price confirmed before booking.",
    summary: "Prepare a rental property for key handover with a cleaning scope based on its size, condition, contents and any inspection priorities.",
    signsTitle: "When end of tenancy cleaning may help",
    signs: ["Keys are due back and the property needs preparing for handover.", "A landlord or agent has requested attention to kitchens, bathrooms or living spaces.", "The property is furnished, has access constraints or needs add-ons discussed before a date is agreed."],
    process: [["Share the property details", "Tell us the property type, bedroom count, condition, furniture status, postcode and preferred handover date."], ["Confirm the cleaning scope", "Discuss the rooms, access information and any priorities such as appliances, carpets or specific areas."], ["Agree the booking", "We confirm the full price and suitable arrangement before any work is booked."]],
    price: "Starting from £79 for a studio flat.",
    priceFactors: ["Bedroom count, property condition and furnished or unfurnished status.", "Appliances, carpets, upholstery or other requested add-ons.", "Access, parking, key collection and the timing of handover."],
    prevention: ["Keep an inspection checklist and note priorities before the cleaning date.", "Remove personal belongings where possible so agreed areas are accessible.", "Share key, parking and access details early to avoid delays."],
    faqs: [{ question: "What is included in end of tenancy cleaning?", answer: "The final scope depends on the property and confirmed requirements. Customers commonly discuss kitchens, bathrooms, bedrooms, living spaces, floors and accessible internal surfaces." }, { question: "How much does end of tenancy cleaning cost?", answer: "Standard studio cleaning starts from £79. The final price depends on property size, condition, access, contents and any requested add-ons, and is confirmed before booking." }, { question: "Can I arrange cleaning around key handover?", answer: "Yes. Share the preferred date and any key or access requirements when you contact us so the arrangement can be discussed." }],
  }),
  "pest-control-services/rat-control": page({
    title: "Rat Control", description: "Rat control in London for homes, rental properties and businesses. Starting from £109; treatment requirements are confirmed before booking.", summary: "If you have seen rats, droppings, gnaw marks or repeated activity, describe the affected areas so the right next step can be discussed.", signsTitle: "Possible signs of a rat problem", signs: ["Droppings, gnaw marks or damaged food packaging.", "Scratching or movement in lofts, walls, cupboards or under floors.", "Rats seen near bins, kitchens, gardens or building entry points."], process: [["Describe the activity", "Tell us where signs appear, when you first noticed them and whether the problem is indoors or outdoors."], ["Review the property factors", "Access, entry points, extent of activity and property use help determine the appropriate approach."], ["Confirm treatment and follow-up", "The full price and whether further visits may be needed are confirmed before booking."]], price: "Starting from £109.", priceFactors: ["Severity and spread of activity.", "Number of affected rooms or external areas.", "Access, likely entry points and whether further visits are needed."], prevention: ["Keep food sealed and remove accessible waste.", "Report gaps around pipes, doors and external openings for assessment.", "Avoid handling rodents or droppings without appropriate precautions."], faqs: [{ question: "What are common signs of rats?", answer: "Common signs include droppings, gnaw marks, noises in voids, damage to food packaging and sightings near waste or entry points." }, { question: "How much does rat control cost?", answer: "Rat control starts from £109 for standard cases. Severity, property access, affected areas and follow-up needs can change the final quote." }, { question: "Can rat treatment need more than one visit?", answer: "Yes. Further visits may be needed depending on the infestation and the treatment plan confirmed for the property." }],
  }),
  "pest-control-services/mice-control": page({
    title: "Mice Control", description: "Mice control in London for homes, rental properties and businesses. Starting from £99; final treatment requirements confirmed before booking.", summary: "Mice can be active in kitchens, cupboards, walls and storage areas. Explain what you have seen and where activity is occurring.", signsTitle: "Possible signs of mice", signs: ["Small droppings in cupboards, kitchens or storage areas.", "Scratching sounds in walls, ceilings or under floors.", "Chewed packaging, gaps around services or a persistent musky smell."], process: [["Report the signs", "Share the affected rooms, the timing of activity and any sightings or damage."], ["Assess the likely scope", "Property layout, access and signs of entry help shape the treatment discussion."], ["Arrange the agreed response", "The full price and any potential additional visits are confirmed before work is booked."]], price: "Starting from £99.", priceFactors: ["Number of rooms and the extent of activity.", "Likely entry points and access to them.", "Whether monitoring or follow-up visits are required."], prevention: ["Store dry food in sealed containers and clear crumbs promptly.", "Keep cupboards and service areas accessible for assessment.", "Note gaps around pipes or skirting so they can be discussed."], faqs: [{ question: "How do I know if I have mice?", answer: "Small droppings, scratching in voids, chewed packaging and sightings in kitchens or storage areas are common signs." }, { question: "How much does mice control cost?", answer: "Mice control starts from £99 for standard cases. The final quote depends on the property, extent of activity, access and follow-up needs." }, { question: "Will mice control require another visit?", answer: "It may. The need for further visits depends on the infestation and is discussed before booking." }],
  }),
  "pest-control-services/bed-bug-treatment": page({
    title: "Bed Bug Treatment", description: "Bed bug treatment in London for homes and rental properties. Starting from £149; treatment scope and visits confirmed before booking.", summary: "Bites, spotting around bedding and insects near beds or furniture can be stressful. Provide clear details without trying to diagnose the issue alone.", signsTitle: "Possible signs of bed bugs", signs: ["Small blood spots or dark marks on bedding, mattresses or bed frames.", "Bites noticed after sleeping, though bites alone do not confirm bed bugs.", "Live insects, shed skins or activity around beds, sofas or luggage."], process: [["Describe what you have noticed", "Tell us the rooms affected, signs found and when the concern began."], ["Discuss preparation and treatment", "The property layout, affected furnishings and treatment requirements are reviewed before a booking is agreed."], ["Confirm visits and aftercare", "We confirm the price, any preparation steps and whether more than one visit may be needed."]], price: "Starting from £149.", priceFactors: ["Number of affected rooms and furnishings.", "Evidence and extent of activity.", "Preparation requirements and any follow-up visits."], prevention: ["Avoid moving bedding or furniture between rooms before advice is given.", "Keep inspected items separate and follow agreed preparation guidance.", "Check luggage and second-hand furniture carefully after travel or purchase."], faqs: [{ question: "What are signs of bed bugs?", answer: "Possible signs include dark spotting, shed skins, live insects and activity around beds or upholstered furniture. Bites alone are not proof." }, { question: "How much does bed bug treatment cost?", answer: "Bed bug treatment starts from £149. The final quote depends on affected rooms, furnishings, preparation and the treatment plan." }, { question: "Can bed bug treatment require more than one visit?", answer: "Yes. Treatment may require more than one visit depending on the infestation and plan confirmed for the property." }],
  }),
  "pest-control-services/cockroach-control": page({
    title: "Cockroach Control", description: "Cockroach control in London for homes, rentals and business premises. Starting from £119; final treatment plan confirmed before booking.", summary: "Cockroaches are often noticed around kitchens, bathrooms, appliances and warm utility areas. Describe where and how often activity occurs.", signsTitle: "Possible signs of cockroaches", signs: ["Live insects seen in kitchens, bathrooms, cupboards or around appliances.", "Small dark droppings or egg cases in sheltered areas.", "Activity that is more noticeable at night or around food and moisture sources."], process: [["Report locations and timing", "Tell us which rooms are affected, when activity is seen and any evidence you have noticed."], ["Review the treatment needs", "Property use, affected areas, hygiene access and the level of activity inform the treatment discussion."], ["Confirm the plan", "We confirm the full quote, preparation requirements and potential need for follow-up before booking."]], price: "Starting from £119.", priceFactors: ["Extent of activity and number of affected spaces.", "Property type, food areas and access around appliances.", "Preparation, treatment method and additional visits."], prevention: ["Remove food residue and keep waste covered.", "Fix moisture issues where possible and keep sinks dry overnight.", "Avoid moving items from affected rooms until advice is provided."], faqs: [{ question: "Where are cockroaches commonly found?", answer: "They are often reported in kitchens, bathrooms, cupboards, utility areas and around appliances where food, warmth or moisture are present." }, { question: "How much does cockroach control cost?", answer: "Cockroach treatment starts from £119. Final cost depends on the extent of activity, affected areas, access and required follow-up." }, { question: "Can cockroach treatment need more than one visit?", answer: "Yes. Further treatment may be needed depending on the infestation and the plan confirmed for the property." }],
  }),
  "pest-control-services/ant-treatment": page({
    title: "Ant Treatment", description: "Ant treatment in London for homes, gardens and business premises. Starting from £69; final treatment requirements confirmed before booking.", summary: "Repeated ant trails in kitchens, entry points or outdoor areas can be disruptive. Explain where activity starts and where ants are travelling.", signsTitle: "When to consider ant treatment", signs: ["Visible trails around food, sinks, doors, windows or skirting.", "Recurring activity from a garden, patio, wall gap or other entry point.", "Ants appearing in multiple rooms or around a business food area."], process: [["Map the activity", "Tell us where ants have been seen, their travel route if known and when activity is most noticeable."], ["Consider the surroundings", "Indoor and outdoor areas, access and likely entry points are reviewed to discuss the appropriate treatment."], ["Confirm the visit", "We confirm the final quote and any relevant preparation or access details before booking."]], price: "Starting from £69.", priceFactors: ["Whether activity is indoors, outdoors or both.", "Number of affected rooms or entry areas.", "Access to likely trails, nests or entry points."], prevention: ["Wipe food spills and store food in sealed containers.", "Remove standing water and keep bins closed.", "Note recurring entry points so they can be discussed."], faqs: [{ question: "Why are ants coming into my property?", answer: "Ants may be attracted by food, water and shelter, often using small gaps around doors, windows, walls or service points." }, { question: "How much does ant treatment cost?", answer: "Ant treatment starts from £69 for standard cases. The final quote depends on affected locations, access and the treatment required." }, { question: "Can ants return after treatment?", answer: "New activity can occur if food sources or entry points remain available. Prevention guidance and property-specific advice can help reduce repeat activity." }],
  }),
  "pest-control-services/flea-treatment": page({
    title: "Flea Treatment", description: "Flea treatment in London for homes and rental properties. Starting from £89; property details and treatment requirements confirmed before booking.", summary: "Fleas can be noticed through bites, pet activity or movement in carpets and soft furnishings. Tell us which rooms and items are affected.", signsTitle: "Possible signs of fleas", signs: ["Bites noticed on people or pets, particularly around ankles or lower legs.", "Small insects seen in pet bedding, carpets, rugs or upholstery.", "Activity continuing after pets have been treated or areas cleaned."], process: [["Describe the affected areas", "Share the rooms, flooring, furnishings and pet-related details that may be relevant."], ["Review preparation", "The treatment discussion considers property size, soft furnishings and any preparation required."], ["Confirm the arrangement", "We confirm the price, treatment scope and any follow-up requirements before booking."]], price: "Starting from £89.", priceFactors: ["Number of rooms, carpets and soft furnishings.", "Pet areas and the extent of activity.", "Preparation and whether a further visit is required."], prevention: ["Follow veterinary advice for pets where relevant.", "Wash pet bedding and vacuum carpets and upholstery regularly.", "Empty vacuum contents safely after cleaning affected areas."], faqs: [{ question: "How do I know if I have fleas?", answer: "Possible signs include bites, flea activity around pets, or small insects in pet bedding, carpets and upholstery. Other causes are possible, so share the signs you have noticed." }, { question: "How much does flea treatment cost?", answer: "Flea treatment starts from £89. The final quote depends on property size, affected rooms, soft furnishings and the treatment plan." }, { question: "Do pets need separate care?", answer: "Pet health should be discussed with a qualified veterinary professional. Tell us about pets and their areas so treatment requirements can be considered." }],
  }),
  "pest-control-services/wasp-treatment": page({
    title: "Wasp Treatment", description: "Wasp treatment and nest removal in London. Starting from £59; location, access and final service scope confirmed before booking.", summary: "A visible nest or repeated wasp activity around a roofline, loft, garden or wall opening should be described from a safe distance.", signsTitle: "Possible signs of a wasp nest", signs: ["Repeated wasp flight to one gap, roofline, loft area, shed or wall opening.", "A visible papery nest in a sheltered location.", "Activity near entrances, outdoor seating or areas used by children or pets."], process: [["Tell us the nest location", "Describe where activity is happening, whether the nest is visible and how safely the area can be accessed."], ["Review access and risk", "Height, location, surrounding activity and property access inform the service discussion."], ["Confirm treatment", "The final price and suitable arrangement are confirmed before booking."]], price: "Starting from £59.", priceFactors: ["Nest location, height and access conditions.", "Whether the nest is visible and safely reachable.", "Property layout and any special access requirements."], prevention: ["Keep away from active nests and do not block the entrance.", "Keep food and drinks covered outdoors where wasps are active.", "Seek urgent medical help if someone has signs of a severe allergic reaction."], faqs: [{ question: "Should I remove a wasp nest myself?", answer: "Avoid disturbing, blocking or attempting to remove an active nest yourself. Describe the location from a safe distance so the appropriate next step can be discussed." }, { question: "How much does wasp treatment cost?", answer: "Wasp treatment starts from £59. The final quote depends on nest location, height, access and the treatment required." }, { question: "Can you help if the nest is in a loft or roofline?", answer: "Tell us where the activity is occurring and what access is available. Suitability and the arrangement can then be reviewed before booking." }],
  }),
  "pest-control-services/squirrel-control": page({ title: "Squirrel Control", description: "Squirrel control in London for homes and properties. Starting price is confirmed after the property and access requirements are reviewed.", summary: "Loft noises, gnawed timbers or repeated entry around rooflines can indicate squirrel activity. Describe the location and access available.", signsTitle: "Possible signs of squirrel activity", signs: ["Scratching or running sounds in a loft or roof void.", "Damage around rooflines, vents, wiring or timber.", "A squirrel repeatedly entering the same external gap."], process: [["Describe the location", "Share where activity is heard or seen and whether access to a loft or roof area is available."], ["Review safe access", "The entry point, height, condition and property layout determine what can be discussed."], ["Confirm the plan", "The service scope, quote and any follow-up needs are confirmed before booking."]], price: "A property-specific quote is confirmed before booking.", priceFactors: ["Loft or roof access and height.", "Evidence of entry points and damage.", "The treatment and exclusion work required."], prevention: ["Keep roof and loft access information available for discussion.", "Record recurring entry points from a safe distance.", "Do not block an active entry point without professional advice."], faqs: [{ question: "What are signs of squirrels in a loft?", answer: "Common reports include daytime scratching or running noises, gnaw damage and repeated activity near a roofline or vent." }, { question: "What affects squirrel-control pricing?", answer: "Access, location, extent of activity and the work required to address entry points affect the final quote." }, { question: "Can I block the entry hole myself?", answer: "Do not block an active entry point without advice, as this may create further issues inside the property." }] }),
  "pest-control-services/spider-treatment": page({ title: "Spider Treatment", description: "Spider treatment in London for homes and properties. Describe recurring spider activity and affected areas for a property-specific service discussion.", summary: "Repeated webs or spiders in the same rooms, corners or external entry areas can be assessed through a clear description of the property and activity.", signsTitle: "When spider treatment may help", signs: ["Repeated webs in the same internal corners, cupboards or outbuildings.", "Frequent spiders in particular rooms or near doors and windows.", "Activity associated with cluttered storage or external entry areas."], process: [["Describe the pattern", "Tell us where spiders or webs repeatedly appear and whether the activity is indoors, outdoors or both."], ["Review the spaces", "Access, affected rooms and property layout help determine the appropriate service discussion."], ["Agree the arrangement", "Any treatment scope and final price are confirmed before booking."]], price: "A property-specific quote is confirmed before booking.", priceFactors: ["Number of affected rooms or external areas.", "Access to high, enclosed or storage spaces.", "Extent and recurrence of activity."], prevention: ["Vacuum webs and keep storage areas uncluttered.", "Seal obvious gaps around windows, doors and service pipes where appropriate.", "Reduce outdoor lighting that attracts insects near entry points."], faqs: [{ question: "Why do spiders keep appearing?", answer: "Spiders may return where prey insects, shelter and entry points are available. Describing the pattern helps identify relevant next steps." }, { question: "Can treatment cover lofts or garages?", answer: "Tell us which areas are affected and what access is available so suitability can be discussed." }, { question: "What affects the quote?", answer: "Affected areas, access and the extent of recurring activity inform the final service discussion." }] }),
  "pest-control-services/silverfish-treatment": page({ title: "Silverfish Treatment", description: "Silverfish treatment in London for homes and rental properties. Report activity in damp or storage areas for a property-specific quote.", summary: "Silverfish are commonly noticed in bathrooms, kitchens, cupboards and damp spaces. Describe the room, moisture conditions and activity you have seen.", signsTitle: "Possible signs of silverfish", signs: ["Small, fast-moving insects in bathrooms, kitchens or cupboards.", "Activity around damp, paper, stored fabrics or food areas.", "Repeated sightings in warm or humid spaces."], process: [["Report the rooms", "Share where insects are seen and whether dampness or storage conditions may be relevant."], ["Discuss property conditions", "Affected areas, access and the extent of activity guide the treatment discussion."], ["Confirm treatment", "The service scope and final price are confirmed before booking."]], price: "A property-specific quote is confirmed before booking.", priceFactors: ["Number of rooms and extent of activity.", "Dampness, storage conditions and access.", "Treatment method and follow-up requirements."], prevention: ["Improve ventilation and address moisture sources where possible.", "Keep paper, fabrics and dry goods in sealed storage.", "Reduce clutter in cupboards and damp-prone areas."], faqs: [{ question: "Where do silverfish live?", answer: "They are often reported in humid or sheltered areas such as bathrooms, kitchens, cupboards and storage spaces." }, { question: "Are silverfish linked to damp?", answer: "Moisture and humidity can make a property more suitable for silverfish, so these conditions are useful to mention." }, { question: "What affects treatment cost?", answer: "Affected rooms, extent of activity, access and property conditions affect the final quote." }] }),
  "pest-control-services/moth-treatment": page({ title: "Moth Treatment", description: "Moth treatment in London for homes and rental properties. Describe moth activity or fabric damage for a property-specific service discussion.", summary: "Moths, larvae, shed cases or damage to natural fabrics and stored items may need a targeted property review.", signsTitle: "Possible signs of moth activity", signs: ["Small moths, larvae or cases in wardrobes, carpets or stored textiles.", "Holes or thinning in natural-fibre garments, rugs or upholstery.", "Activity in dark storage areas or around rarely moved furnishings."], process: [["Describe items and rooms", "Tell us which textiles, furnishings or storage areas are affected."], ["Review the extent", "The materials, rooms and accessibility inform the treatment discussion."], ["Confirm the scope", "We confirm the price and any preparation requirements before booking."]], price: "A property-specific quote is confirmed before booking.", priceFactors: ["Affected textiles, carpets or furnishings.", "Number of rooms and storage areas.", "Preparation, access and treatment requirements."], prevention: ["Clean and inspect stored natural-fibre items regularly.", "Vacuum carpets, rugs and wardrobe edges.", "Store clean seasonal clothing in sealed containers."], faqs: [{ question: "How can I tell if moths are damaging fabrics?", answer: "Larvae, cases, holes and thinning in natural fibres can be signs. Share photos or details through the contact route if requested." }, { question: "Can moths affect carpets?", answer: "Some moth activity can involve natural-fibre carpets and rugs. Mention the material and affected area when contacting us." }, { question: "What affects treatment price?", answer: "The number of rooms, affected materials, accessibility and required treatment affect the final quote." }] }),
  "pest-control-services/carpet-beetles": page({ title: "Carpet Beetle Treatment", description: "Carpet beetle treatment in London for homes and rental properties. Report larvae, shed skins or fabric damage for a tailored service discussion.", summary: "Carpet beetle larvae may be found near carpets, skirting, wardrobes and natural fibres. Explain what you have found and where.", signsTitle: "Possible signs of carpet beetles", signs: ["Small hairy larvae or shed skins near carpets and skirting.", "Damage to natural-fibre textiles, stored clothing or upholstery.", "Activity in quiet, dark edges of rooms or cupboards."], process: [["Identify affected areas", "Tell us where larvae, skins or damage have been noticed."], ["Review material and access", "Room layout, textiles and accessible edges help shape the service discussion."], ["Confirm the treatment", "The final scope, price and preparation requirements are agreed before booking."]], price: "A property-specific quote is confirmed before booking.", priceFactors: ["Affected rooms, carpets and furnishings.", "Extent of larvae or fabric damage.", "Preparation and treatment access."], prevention: ["Vacuum carpet edges, skirting and storage areas frequently.", "Clean and inspect natural-fibre items before storing them.", "Remove accumulated lint, hair and dust from quiet corners."], faqs: [{ question: "What do carpet beetle larvae look like?", answer: "They are often described as small, bristly larvae or shed skins near carpets, skirting and natural-fibre items." }, { question: "Can carpet beetles damage clothing?", answer: "Larvae can damage some natural-fibre textiles. Mention the materials and locations affected." }, { question: "How is pricing decided?", answer: "Affected areas, furnishings, accessibility and the required treatment determine the final quote." }] }),
  "pest-control-services/woodworm-treatment": page({ title: "Woodworm Treatment", description: "Woodworm treatment in London for properties with suspected timber damage. Describe the timber, holes and dust for a property-specific assessment.", summary: "Small holes and fresh-looking dust in timber can require a careful discussion of the affected material, location and condition.", signsTitle: "Possible signs of woodworm", signs: ["Small round holes in exposed timber or furniture.", "Fresh dust-like frass near holes or beneath timber.", "Damage or weakness in floorboards, roof timbers or furniture."], process: [["Describe the timber", "Tell us the location, type of timber, visible holes and whether fresh dust is present."], ["Review access and condition", "Affected structure, access and evidence of activity determine the assessment discussion."], ["Confirm scope", "Any inspection, treatment scope and final price are agreed before booking."]], price: "A property-specific quote is confirmed before booking.", priceFactors: ["Location and accessibility of timber.", "Evidence of active activity and extent of damage.", "Whether structural assessment or additional treatment is needed."], prevention: ["Keep timber areas ventilated and address persistent dampness.", "Avoid covering or painting affected timber before it is reviewed.", "Record the location of holes or fresh dust for discussion."], faqs: [{ question: "How do I know if woodworm is active?", answer: "Fresh frass near holes can be a useful sign, but activity and treatment needs should be assessed from the property details." }, { question: "Can woodworm affect structural timber?", answer: "It can affect different timber elements. Mention whether the concern is furniture, floorboards, loft timber or another area." }, { question: "What affects the price?", answer: "Timber location, access, evidence of activity and treatment scope determine the final quote." }] }),
  "pest-control-services/general-fogging": page({ title: "General Fogging", description: "General fogging in London for suitable pest-control situations. Property, pest concern and treatment suitability are reviewed before booking.", summary: "Fogging is not automatically appropriate for every pest issue. Describe the problem, affected spaces and property use so suitability can be discussed.", signsTitle: "Information needed before fogging", signs: ["The pest concern or signs observed.", "Rooms affected and the people, pets or business activity using them.", "Any ventilation, access or preparation constraints."], process: [["Describe the concern", "Tell us the pest issue, affected areas and property type."], ["Assess suitability", "The treatment method and preparation requirements are discussed before a service is offered."], ["Confirm the arrangement", "The final scope, price and aftercare information are confirmed before booking."]], price: "A property-specific quote is confirmed before booking.", priceFactors: ["Pest type and whether fogging is appropriate.", "Property size, rooms and preparation needs.", "Access, ventilation and any follow-up required."], prevention: ["Do not use unapproved products in occupied spaces.", "Follow any agreed preparation and re-entry guidance exactly.", "Address food, waste, moisture or access factors linked to the pest issue."], faqs: [{ question: "Is fogging suitable for every pest problem?", answer: "No. The pest type, property use and treatment requirements must be reviewed before fogging is considered." }, { question: "What preparation is needed?", answer: "Preparation depends on the property and agreed method. Instructions should be confirmed before any booking." }, { question: "How is the price set?", answer: "Suitability, property size, affected rooms, access and the required treatment determine the final quote." }] }),
  "pest-control-services/dead-pest-removal": page({ title: "Dead Pest Removal", description: "Dead pest removal in London for homes and properties. Describe the location, pest if known and safe access for a property-specific arrangement.", summary: "If a dead pest needs removing, provide the location, the pest type if known and any access restrictions without handling it unnecessarily.", signsTitle: "Details to share", signs: ["Where the animal or pest is located.", "Whether it is indoors, outdoors, in a loft or another restricted area.", "Any odour, contamination concern or access limitation."], process: [["Describe the location", "Tell us where the pest is and whether it can be safely accessed."], ["Review the arrangement", "Property access, disposal requirements and any associated pest concern are discussed."], ["Confirm service", "The final price and suitable arrangement are confirmed before booking."]], price: "A property-specific quote is confirmed before booking.", priceFactors: ["Location and access difficulty.", "Pest type and condition if known.", "Any sanitation or follow-up requirements."], prevention: ["Avoid direct contact and keep children and pets away.", "Do not disturb an inaccessible carcass in a void or roof area.", "Report recurring activity so the underlying issue can be discussed."], faqs: [{ question: "Can you remove a dead pest from a loft?", answer: "Tell us the exact location and access available so suitability can be reviewed before booking." }, { question: "Should I handle a dead animal myself?", answer: "Avoid unnecessary direct handling. Explain the location and condition so the appropriate arrangement can be discussed." }, { question: "Does removal address the original pest issue?", answer: "Removal and the underlying cause can be discussed separately; describe any recurring signs or entry points." }] }),
  "pest-control-services/pest-inspection": page({ title: "Pest Inspection", description: "Pest inspections in London for properties with unexplained pest signs. Describe activity, affected areas and property type for a tailored review.", summary: "When the pest type or extent of a problem is unclear, an inspection discussion can start with the signs, rooms and timing you have observed.", signsTitle: "When an inspection may be useful", signs: ["Unidentified droppings, damage, noises or insects.", "Signs appearing in several parts of the property.", "A recurring problem where the likely entry point is unclear."], process: [["Share the evidence", "Describe signs, affected rooms and when activity occurs."], ["Discuss inspection needs", "Property layout, access and the information available help determine the next step."], ["Confirm the visit", "Any inspection scope, quote and follow-on work are discussed before booking."]], price: "A property-specific quote is confirmed before booking.", priceFactors: ["Property size and number of areas to inspect.", "Access to lofts, voids, external spaces or commercial areas.", "Whether follow-on treatment is required."], prevention: ["Keep a short record of sightings, dates and affected areas.", "Avoid disturbing signs before they can be discussed.", "Make safe access details available when contacting us."], faqs: [{ question: "Can I book an inspection if I do not know the pest?", answer: "Yes. Describe the signs and affected areas rather than guessing the pest type." }, { question: "What should I note before an inspection?", answer: "Useful details include sightings, noises, droppings, damage, locations, timing and access limitations." }, { question: "Does an inspection include treatment?", answer: "Any follow-on service depends on the findings and must be discussed and confirmed separately." }] }),
  "pest-control-services/commercial-pest-control": page({ title: "Commercial Pest Control", description: "Commercial pest control in London for business premises. Starting from £49 per month; service requirements and scope confirmed before booking.", summary: "Businesses can describe their premises, pest concerns, operational hours and access needs so an appropriate service arrangement can be discussed.", signsTitle: "Commercial information to provide", signs: ["Premises type and operating hours.", "Pest signs, affected areas and any food-handling or public-facing spaces.", "Site access, contact arrangements and recurring concerns."], process: [["Describe the premises", "Tell us the business type, property layout, affected areas and operational constraints."], ["Review service requirements", "The pest concern, access and monitoring or visit needs guide the discussion."], ["Confirm the arrangement", "We confirm scope, frequency, final price and reporting requirements before booking."]], price: "Starting from £49 per month.", priceFactors: ["Premises type, size and operating hours.", "Pest risk, affected areas and visit frequency.", "Monitoring, reporting and access requirements."], prevention: ["Maintain waste, food-storage and cleaning controls appropriate to the premises.", "Record sightings and locations for the responsible site contact.", "Keep service and delivery areas accessible for inspection."], faqs: [{ question: "What businesses can request commercial pest control?", answer: "Businesses can describe their premises and requirements; suitability is confirmed based on the actual site and service needs." }, { question: "How much does commercial pest control cost?", answer: "Commercial pest control starts from £49 per month. The final price depends on premises, risk, visit frequency and the agreed scope." }, { question: "Can visits be planned around trading hours?", answer: "Share operating hours and access requirements so a suitable arrangement can be discussed before booking." }] }),
} as const;

export type ApprovedServiceKey = keyof typeof approvedServicePages;

const cleaningPage = (title: string, summary: string, focus: string, preparation: string, priceFactor: string) => page({
  title,
  description: `${title} in London from Bestone Services Ltd. Discuss the property, service scope and final price before booking.`,
  summary,
  signsTitle: "When this service may help",
  signs: [focus, `Tell us about the property, access and the areas that need attention.`, "Share a preferred date so the service arrangement can be discussed."],
  process: [["Share the relevant details", `Explain the property, the areas involved and any timing or access requirements for ${title.toLowerCase()}.`], ["Confirm the scope", "The requested work, any preparation and the price factors can be discussed for the actual property."], ["Agree the booking", "We confirm the full price and service arrangement before work is booked."]],
  price: "A property-specific quote is confirmed before booking.",
  priceFactors: [priceFactor, "Property size, condition, access and requested add-ons.", "Parking, key collection, timing and any specialist requirements."],
  prevention: [preparation, "Make the agreed areas accessible before the visit.", "Share relevant access or parking information early."],
  faqs: [{ question: `What information is needed for ${title.toLowerCase()}?`, answer: "Tell us about the property, the affected areas or items, condition, access, postcode or area and preferred timing." }, { question: `How is the price for ${title.toLowerCase()} decided?`, answer: `The property, scope, condition, access and any specialist requirements determine the final quote. ${priceFactor}` }, { question: "Is the booking confirmed immediately?", answer: "No. The full price, availability and service arrangement are confirmed before work is booked." }],
});

export const approvedCleaningServicePages = {
  "cleaning-services/domestic-cleaning": cleaningPage("Domestic Cleaning", "Practical home cleaning can be discussed around the rooms, priorities and household access that apply to your property.", "A home needs a one-off or tailored clean across everyday living spaces.", "Clear personal items and identify any rooms that need particular attention.", "The number of rooms, condition and requested cleaning priorities affect the quote."),
  "cleaning-services/regular-cleaning": cleaningPage("Regular Cleaning", "For ongoing household cleaning, explain the preferred frequency, rooms and practical access details for a suitable discussion.", "A property needs recurring support for everyday cleaning tasks.", "Keep a simple list of recurring priorities for kitchens, bathrooms and shared spaces.", "Visit frequency, property size and the agreed recurring scope affect the quote."),
  "cleaning-services/one-off-cleaning-services": cleaningPage("One-off Cleaning Services", "A one-off clean can be arranged around a particular event, property change or set of rooms needing attention.", "A home needs focused cleaning without an ongoing schedule.", "List the rooms, surfaces or event-related priorities before contacting us.", "Property condition, scope and any time-sensitive requirements affect the quote."),
  "cleaning-services/after-builders-cleaning": cleaningPage("After Builders Cleaning", "Post-work cleaning can be discussed once the building work is complete and the areas, dust and access conditions are clear.", "Dust, residue and construction-related mess remain after building or decorating work.", "Ensure work is complete and identify any fragile finishes or restricted areas.", "The amount of residue, property size, access and specialist surface needs affect the quote."),
  "cleaning-services/carpet-cleaning": cleaningPage("Carpet Cleaning", "Carpet cleaning can be discussed for marked, high-traffic or move-out areas, with material and condition considered first.", "Carpets have marks, odours, high-traffic wear or need attention before handover.", "Point out stains, pet areas and the carpet material if known.", "Number of rooms, carpet material, staining and drying/access conditions affect the quote."),
  "cleaning-services/oven-cleaning-service": cleaningPage("Oven Cleaning Service", "Oven cleaning can be discussed for built-in or freestanding appliances, including the appliance type and level of residue.", "An oven has baked-on residue, grease or needs attention before a handover.", "Let the appliance cool and mention the model or range type if known.", "Appliance size, condition, removable parts and access affect the quote."),
  "cleaning-services/appliance-cleaning": cleaningPage("Appliance Cleaning", "Appliance cleaning can be discussed for the specific item, its condition and the accessible components requiring attention.", "A kitchen or household appliance needs detailed cleaning before use or property handover.", "Identify the appliance type and any areas of heavy residue or restricted access.", "Appliance type, size, condition and required disassembly or access affect the quote."),
  "cleaning-services/mattress-cleaning-service": cleaningPage("Mattress Cleaning Service", "Mattress cleaning can be discussed around the mattress size, material, staining and access within the property.", "A mattress needs freshening after spills, marks or general use.", "Tell us the mattress size, material and any marks or odours to consider.", "Mattress size, material, condition and access to the room affect the quote."),
  "cleaning-services/upholstery-cleaning": cleaningPage("Upholstery Cleaning", "Sofa, chair and other upholstery cleaning depends on fabric type, item size, staining and the space available for access.", "Upholstered furniture has marks, odours or high-use areas needing attention.", "Identify the fabric, item size and any known stains before contacting us.", "Fabric type, number of items, staining and access affect the quote."),
  "cleaning-services/window-cleaning": cleaningPage("Window Cleaning", "Window cleaning can be discussed for internal or external glass, property height, access and the number of windows.", "Windows need cleaning after weather, construction work or a property handover.", "Tell us whether cleaning is internal, external or both and describe access safely.", "Window count, height, access equipment and internal/external scope affect the quote."),
  "cleaning-services/holiday-rental-cleaning": cleaningPage("Holiday Rental Cleaning", "Holiday-rental cleaning can be planned around changeover dates, guest-ready priorities, linen arrangements and property access.", "A short-let property needs preparing between guests or before an arrival.", "Share turnover timing, property size and any linen or inventory priorities.", "Changeover timing, bedrooms, linen needs and property condition affect the quote."),
  "cleaning-services/range-cooker-cleaning": cleaningPage("Range Cooker Cleaning", "Range cooker cleaning can be discussed with the cooker type, size, fuel arrangement and accessible components in mind.", "A range cooker needs attention to ovens, hob areas or removable components.", "Tell us the range type and number of ovens or compartments if known.", "Cooker size, number of ovens, condition and access affect the quote."),
  "cleaning-services/aga-cleaning": cleaningPage("AGA Cleaning", "AGA cleaning requires the appliance type, condition and access arrangements to be discussed before a suitable scope is agreed.", "An AGA appliance needs specialist cleaning attention for its accessible areas.", "Identify the AGA model or configuration and any areas of concern.", "Model, condition, accessible components and required preparation affect the quote."),
  "cleaning-services/bbq-cleaning": cleaningPage("BBQ Cleaning", "BBQ cleaning can be discussed for the appliance size, fuel type, condition and outdoor access arrangements.", "A barbecue has grease, residue or seasonal build-up before use.", "Allow the barbecue to cool and identify its type and location.", "BBQ size, fuel type, residue level and outdoor access affect the quote."),
  "cleaning-services/curtains-and-blinds-cleaning": cleaningPage("Curtains and Blinds Cleaning", "Curtain and blind cleaning depends on material, installation, dimensions and whether removal or specialist handling is required.", "Window coverings show dust, marks or need cleaning as part of a property refresh.", "Tell us the type of curtain or blind, dimensions and any material information.", "Material, dimensions, quantity and removal/access requirements affect the quote."),
  "cleaning-services/leather-sofa-cleaning-services": cleaningPage("Leather Sofa Cleaning Services", "Leather sofa cleaning should account for leather type, condition, colouring and any marks before a cleaning approach is discussed.", "Leather seating has surface marks, dirt or wear that needs careful cleaning.", "Share the sofa size, leather type if known and the condition of affected areas.", "Leather type, item size, condition and specialist care requirements affect the quote."),
  "cleaning-services/conservatory-cleaning": cleaningPage("Conservatory Cleaning", "Conservatory cleaning can be discussed around glass, frames, flooring, height and the internal or external areas required.", "A conservatory needs seasonal cleaning or attention after weather and general use.", "Describe the glass, frames, roof access and any restricted areas safely.", "Size, glazing, height, access and internal/external scope affect the quote."),
  "cleaning-services/gutter-cleaning": cleaningPage("Gutter Cleaning", "Gutter cleaning requires a clear discussion of property height, gutter access, visible blockages and safe working conditions.", "Gutters show overflow, debris or blockages that need safe attention.", "Describe the property height, affected side and visible issue from ground level.", "Height, length, access, debris and safe working conditions affect the quote."),
  "cleaning-services/home-organising-services": cleaningPage("Home Organising Services", "Home organising can be discussed around rooms, storage goals, household priorities and the level of support wanted.", "A home needs help creating clearer, more practical storage and room systems.", "Identify the rooms, storage challenges and desired outcome before contacting us.", "Number of rooms, amount of belongings, goals and session requirements affect the quote."),
  "cleaning-services/laundry-dry-cleaning": cleaningPage("Laundry and Dry Cleaning", "Laundry and dry-cleaning requirements can be discussed around garment types, collection arrangements and any care-label restrictions.", "Garments, bedding or household textiles need cleaning with suitable handling.", "Check care labels and list delicate, stained or time-sensitive items.", "Item types, quantities, care requirements and collection/delivery arrangements affect the quote."),
} as const;
