import { serviceFaqSchema, type ServiceFaq } from "@/content/service-types";

export type ApprovedServicePage = {
  title: string;
  description: string;
  summary: string;
  signsTitle: string;
  signs: readonly string[];
  process: readonly [string, string][];
  price: string;
  priceFactors: readonly string[];
  prevention: readonly string[];
  faqs: readonly ServiceFaq[];
};

const page = (data: Omit<ApprovedServicePage, "faqs"> & { faqs: readonly { question: string; answer: string }[] }) => ({ ...data, faqs: serviceFaqSchema.array().parse(data.faqs) });

export const approvedServicePages = {
  "cleaning-services/end-of-tenancy-cleaning": page({
    title: "End of Tenancy Cleaning",
    description: "End of tenancy cleaning in London for tenants, landlords and letting agents. Starting from £130 for studio flats; final scope and price confirmed before booking.",
    summary: "Prepare a rental property for key handover with a cleaning scope based on its size, condition, contents and any inspection priorities.",
    signsTitle: "When end of tenancy cleaning may help",
    signs: ["Keys are due back and the property needs preparing for handover.", "A landlord or agent has requested attention to kitchens, bathrooms or living spaces.", "The property is furnished, has access constraints or needs add-ons discussed before a date is agreed."],
    process: [["Share the property details", "Tell us the property type, bedroom count, condition, furniture status, postcode and preferred handover date."], ["Confirm the cleaning scope", "Discuss the rooms, access information and any priorities such as appliances, carpets or specific areas."], ["Agree the booking", "We confirm the full price and suitable arrangement before any work is booked."]],
    price: "Starting from £130 for a studio flat.",
    priceFactors: ["Bedroom count, property condition and furnished or unfurnished status.", "Appliances, carpets, upholstery or other requested add-ons.", "Access, parking, key collection and the timing of handover."],
    prevention: ["Keep an inspection checklist and note priorities before the cleaning date.", "Remove personal belongings where possible so agreed areas are accessible.", "Share key, parking and access details early to avoid delays."],
    faqs: [{ question: "What is included in end of tenancy cleaning?", answer: "The final scope depends on the property and confirmed requirements. Customers commonly discuss kitchens, bathrooms, bedrooms, living spaces, floors and accessible internal surfaces." }, { question: "How much does end of tenancy cleaning cost?", answer: "Standard studio cleaning starts from £130. The final price depends on property size, condition, access, contents and any requested add-ons, and is confirmed before booking." }, { question: "Can I arrange cleaning around key handover?", answer: "Yes. Share the preferred date and any key or access requirements when you contact us so the arrangement can be discussed." }],
  }),
  "pest-control-services/rat-control": page({
    title: "Rat Control", description: "Rat control in London for homes, rental properties and businesses. Starting from £109; treatment requirements are confirmed before booking.", summary: "If you have seen rats, droppings, gnaw marks or repeated activity, describe the affected areas so the right next step can be discussed.", signsTitle: "Possible signs of a rat problem", signs: ["Droppings, gnaw marks or damaged food packaging.", "Scratching or movement in lofts, walls, cupboards or under floors.", "Rats seen near bins, kitchens, gardens or building entry points."], process: [["Describe the activity", "Tell us where signs appear, when you first noticed them and whether the problem is indoors or outdoors."], ["Review the property factors", "Access, entry points, extent of activity and property use help determine the appropriate approach."], ["Confirm treatment and follow-up", "The full price and whether further visits may be needed are confirmed before booking."]], price: "Starting from £109.", priceFactors: ["Severity and spread of activity.", "Number of affected rooms or external areas.", "Access, likely entry points and whether further visits are needed."], prevention: ["Keep food sealed and remove accessible waste.", "Report gaps around pipes, doors and external openings for assessment.", "Avoid handling rodents or droppings without appropriate precautions."], faqs: [{ question: "What are common signs of rats?", answer: "Common signs include droppings, gnaw marks, noises in voids, damage to food packaging and sightings near waste or entry points." }, { question: "How much does rat control cost?", answer: "Rat control starts from £109 for standard cases. Severity, property access, affected areas and follow-up needs can change the final quote." }, { question: "Can rat treatment need more than one visit?", answer: "Yes. Further visits may be needed depending on the infestation and the treatment plan confirmed for the property." }],
  }),
  "pest-control-services/mice-control": page({
    title: "Mice Control", description: "Mice control in London for homes, rental properties and businesses. Starting from £99; final treatment requirements confirmed before booking.", summary: "Mice can be active in kitchens, cupboards, walls and storage areas. Explain what you have seen and where activity is occurring.", signsTitle: "Possible signs of mice", signs: ["Small droppings in cupboards, kitchens or storage areas.", "Scratching sounds in walls, ceilings or under floors.", "Chewed packaging, gaps around services or a persistent musky smell."], process: [["Report the signs", "Share the affected rooms, the timing of activity and any sightings or damage."], ["Assess the likely scope", "Property layout, access and signs of entry help shape the treatment discussion."], ["Arrange the agreed response", "The full price and any potential additional visits are confirmed before work is booked."]], price: "Starting from £99.", priceFactors: ["Number of rooms and the extent of activity.", "Likely entry points and access to them.", "Whether monitoring or follow-up visits are required."], prevention: ["Store dry food in sealed containers and clear crumbs promptly.", "Keep cupboards and service areas accessible for assessment.", "Note gaps around pipes or skirting so they can be discussed."], faqs: [{ question: "How do I know if I have mice?", answer: "Small droppings, scratching in voids, chewed packaging and sightings in kitchens or storage areas are common signs." }, { question: "How much does mice control cost?", answer: "Mice control starts from £99 for standard cases. The final quote depends on the property, extent of activity, access and follow-up needs." }, { question: "Will mice control require another visit?", answer: "It may. The need for further visits depends on the infestation and is discussed before booking." }],
  }),
  "pest-control-services/bed-bug-treatment": page({
    title: "Bed Bug Treatment", description: "Bed bug treatment in London for homes and rental properties. Starting from £149; treatment scope and visits confirmed before booking.", summary: "Bites, spotting around bedding and insects near beds or furniture can be stressful. Provide clear details without trying to diagnose the issue alone.", signsTitle: "Possible signs of bed bugs", signs: ["Small blood spots or dark marks on bedding, mattresses or bed frames.", "Bites noticed after sleeping, though bites alone do not confirm bed bugs.", "Live insects, shed skins or activity around beds, sofas or luggage."], process: [["Describe what you have noticed", "Tell us the rooms affected, signs found and when the concern began."], ["Discuss preparation and treatment", "The property layout, affected furnishings and treatment requirements are reviewed before a booking is agreed."], ["Confirm visits and aftercare", "We confirm the price, any preparation steps and whether more than one visit may be needed."]], price: "Starting from £149.", priceFactors: ["Number of affected rooms and furnishings.", "Evidence and extent of activity.", "Preparation requirements and any follow-up visits."], prevention: ["Avoid moving bedding or furniture between rooms before advice is given.", "Keep inspected items separate and follow agreed preparation guidance.", "Check luggage and second-hand furniture carefully after travel or purchase."], faqs: [{ question: "What are signs of bed bugs?", answer: "Possible signs include dark spotting, shed skins, live insects and activity around beds or upholstered furniture. Bites alone are not proof." }, { question: "How much does bed bug treatment cost?", answer: "Bed bug treatment starts from £149. The final quote depends on affected rooms, furnishings, preparation and the treatment plan." }, { question: "Can bed bug treatment require more than one visit?", answer: "Yes. Treatment may require more than one visit depending on the infestation and plan confirmed for the property." }],
  }),
  "pest-control-services/cockroach-control": page({
    title: "Cockroach Control", description: "Cockroach control in London for homes, rentals and business premises. Starting from £119; final treatment plan confirmed before booking.", summary: "Cockroaches are often noticed around kitchens, bathrooms, appliances and warm utility areas. Describe where and how often activity occurs.", signsTitle: "Possible signs of cockroaches", signs: ["Live insects seen in kitchens, bathrooms, cupboards or around appliances.", "Small dark droppings or egg cases in sheltered areas.", "Activity that is more noticeable at night or around food and moisture sources."], process: [["Report locations and timing", "Tell us which rooms are affected, when activity is seen and any evidence you have noticed."], ["Review the treatment needs", "Property use, affected areas, hygiene access and the level of activity inform the treatment discussion."], ["Confirm the plan", "We confirm the full quote, preparation requirements and potential need for follow-up before booking."]], price: "Starting from £119.", priceFactors: ["Extent of activity and number of affected spaces.", "Property type, food areas and access around appliances.", "Preparation, treatment method and additional visits."], prevention: ["Remove food residue and keep waste covered.", "Fix moisture issues where possible and keep sinks dry overnight.", "Avoid moving items from affected rooms until advice is provided."], faqs: [{ question: "Where are cockroaches commonly found?", answer: "They are often reported in kitchens, bathrooms, cupboards, utility areas and around appliances where food, warmth or moisture are present." }, { question: "How much does cockroach control cost?", answer: "Cockroach treatment starts from £119. Final cost depends on the extent of activity, affected areas, access and required follow-up." }, { question: "Can cockroach treatment need more than one visit?", answer: "Yes. Further treatment may be needed depending on the infestation and the plan confirmed for the property." }],
  }),
  "pest-control-services/ant-treatment": page({
    title: "Ant Treatment", description: "Ant treatment in London for homes, gardens and business premises. Starting from £69; final treatment requirements confirmed before booking.", summary: "Repeated ant trails in kitchens, entry points or outdoor areas can be disruptive. Explain where activity starts and where ants are travelling.", signsTitle: "When to consider ant treatment", signs: ["Visible trails around food, sinks, doors, windows or skirting.", "Recurring activity from a garden, patio, wall gap or other entry point.", "Ants appearing in multiple rooms or around a business food area."], process: [["Map the activity", "Tell us where ants have been seen, their travel route if known and when activity is most noticeable."], ["Consider the surroundings", "Indoor and outdoor areas, access and likely entry points are reviewed to discuss the appropriate treatment."], ["Confirm the visit", "We confirm the final quote and any relevant preparation or access details before booking."]], price: "Starting from £69.", priceFactors: ["Whether activity is indoors, outdoors or both.", "Number of affected rooms or entry areas.", "Access to likely trails, nests or entry points."], prevention: ["Wipe food spills and store food in sealed containers.", "Remove standing water and keep bins closed.", "Note recurring entry points so they can be discussed."], faqs: [{ question: "Why are ants coming into my property?", answer: "Ants may be attracted by food, water and shelter, often using small gaps around doors, windows, walls or service points." }, { question: "How much does ant treatment cost?", answer: "Ant treatment starts from £69 for standard cases. The final quote depends on affected locations, access and the treatment required." }, { question: "Can ants return after treatment?", answer: "New activity can occur if food sources or entry points remain available. Prevention guidance and property-specific advice can help reduce repeat activity." }],
  }),
  "pest-control-services/flea-treatment": page({
    title: "Flea Treatment", description: "Flea treatment in London for homes and rental properties. Starting from £89; property details and treatment requirements confirmed before booking.", summary: "Fleas can be noticed through bites, pet activity or movement in carpets and soft furnishings. Tell us which rooms and items are affected.", signsTitle: "Possible signs of fleas", signs: ["Bites noticed on people or pets, particularly around ankles or lower legs.", "Small insects seen in pet bedding, carpets, rugs or upholstery.", "Activity continuing after pets have been treated or areas cleaned."], process: [["Describe the affected areas", "Share the rooms, flooring, furnishings and pet-related details that may be relevant."], ["Review preparation", "The treatment discussion considers property size, soft furnishings and any preparation required."], ["Confirm the arrangement", "We confirm the price, treatment scope and any follow-up requirements before booking."]], price: "Starting from £89.", priceFactors: ["Number of rooms, carpets and soft furnishings.", "Pet areas and the extent of activity.", "Preparation and whether a further visit is required."], prevention: ["Follow veterinary advice for pets where relevant.", "Wash pet bedding and vacuum carpets and upholstery regularly.", "Empty vacuum contents safely after cleaning affected areas."], faqs: [{ question: "How do I know if I have fleas?", answer: "Possible signs include bites, flea activity around pets, or small insects in pet bedding, carpets and upholstery. Other causes are possible, so share the signs you have noticed." }, { question: "How much does flea treatment cost?", answer: "Flea treatment starts from £89. The final quote depends on property size, affected rooms, soft furnishings and the treatment plan." }, { question: "Do pets need separate care?", answer: "Pet health should be discussed with a qualified veterinary professional. Tell us about pets and their areas so treatment requirements can be considered." }],
  }),
  "pest-control-services/wasp-treatment": page({
    title: "Wasp Treatment", description: "Wasp treatment and nest removal in London. Starting from £59; location, access and final service scope confirmed before booking.", summary: "A visible nest or repeated wasp activity around a roofline, loft, garden or wall opening should be described from a safe distance.", signsTitle: "Possible signs of a wasp nest", signs: ["Repeated wasp flight to one gap, roofline, loft area, shed or wall opening.", "A visible papery nest in a sheltered location.", "Activity near entrances, outdoor seating or areas used by children or pets."], process: [["Tell us the nest location", "Describe where activity is happening, whether the nest is visible and how safely the area can be accessed."], ["Review access and risk", "Height, location, surrounding activity and property access inform the service discussion."], ["Confirm treatment", "The final price and suitable arrangement are confirmed before booking."]], price: "Starting from £59.", priceFactors: ["Nest location, height and access conditions.", "Whether the nest is visible and safely reachable.", "Property layout and any special access requirements."], prevention: ["Keep away from active nests and do not block the entrance.", "Keep food and drinks covered outdoors where wasps are active.", "Seek urgent medical help if someone has signs of a severe allergic reaction."], faqs: [{ question: "Should I remove a wasp nest myself?", answer: "Avoid disturbing, blocking or attempting to remove an active nest yourself. Describe the location from a safe distance so the appropriate next step can be discussed." }, { question: "How much does wasp treatment cost?", answer: "Wasp treatment starts from £59. The final quote depends on nest location, height, access and the treatment required." }, { question: "Can you help if the nest is in a loft or roofline?", answer: "Tell us where the activity is occurring and what access is available. Suitability and the arrangement can then be reviewed before booking." }],
  }),
  "pest-control-services/squirrel-control": page({ title: "Squirrel Control", description: "Squirrel control in London for homes and properties. Starting price is confirmed after the property and access requirements are reviewed.", summary: "Loft noises, gnawed timbers or repeated entry around rooflines can indicate squirrel activity. Describe the location and access available.", signsTitle: "Possible signs of squirrel activity", signs: ["Scratching or running sounds in a loft or roof void.", "Damage around rooflines, vents, wiring or timber.", "A squirrel repeatedly entering the same external gap."], process: [["Describe the location", "Share where activity is heard or seen and whether access to a loft or roof area is available."], ["Review safe access", "The entry point, height, condition and property layout determine what can be discussed."], ["Confirm the plan", "The service scope, quote and any follow-up needs are confirmed before booking."]], price: "A property-specific quote is confirmed before booking.", priceFactors: ["Loft or roof access and height.", "Evidence of entry points and damage.", "The treatment and exclusion work required."], prevention: ["Keep roof and loft access information available for discussion.", "Record recurring entry points from a safe distance.", "Do not block an active entry point without professional advice."], faqs: [{ question: "What are signs of squirrels in a loft?", answer: "Common reports include daytime scratching or running noises, gnaw damage and repeated activity near a roofline or vent." }, { question: "What affects squirrel-control pricing?", answer: "Access, location, extent of activity and the work required to address entry points affect the final quote." }, { question: "Can I block the entry hole myself?", answer: "Do not block an active entry point without advice, as this may create further issues inside the property." }] }),
  "pest-control-services/spider-treatment": page({ title: "Spider Treatment", description: "Spider treatment in London for homes and properties. Describe recurring spider activity and affected areas for a property-specific service discussion.", summary: "Repeated webs or spiders in the same rooms, corners or external entry areas can be assessed through a clear description of the property and activity.", signsTitle: "When spider treatment may help", signs: ["Repeated webs in the same internal corners, cupboards or outbuildings.", "Frequent spiders in particular rooms or near doors and windows.", "Activity associated with cluttered storage or external entry areas."], process: [["Describe the pattern", "Tell us where spiders or webs repeatedly appear and whether the activity is indoors, outdoors or both."], ["Review the spaces", "Access, affected rooms and property layout help determine the appropriate service discussion."], ["Agree the arrangement", "Any treatment scope and final price are confirmed before booking."]], price: "A property-specific quote is confirmed before booking.", priceFactors: ["Number of affected rooms or external areas.", "Access to high, enclosed or storage spaces.", "Extent and recurrence of activity."], prevention: ["Vacuum webs and keep storage areas uncluttered.", "Seal obvious gaps around windows, doors and service pipes where appropriate.", "Reduce outdoor lighting that attracts insects near entry points."], faqs: [{ question: "Why do spiders keep appearing?", answer: "Spiders may return where prey insects, shelter and entry points are available. Describing the pattern helps identify relevant next steps." }, { question: "Can treatment cover lofts or garages?", answer: "Tell us which areas are affected and what access is available so suitability can be discussed." }, { question: "What affects the quote?", answer: "Affected areas, access and the extent of recurring activity inform the final service discussion." }] }),
  "pest-control-services/silverfish-treatment": page({ title: "Silverfish Treatment", description: "Silverfish treatment in London for homes and rental properties. Report activity in damp or storage areas for a property-specific quote.", summary: "Silverfish are commonly noticed in bathrooms, kitchens, cupboards and damp spaces. Describe the room, moisture conditions and activity you have seen.", signsTitle: "Possible signs of silverfish", signs: ["Small, fast-moving insects in bathrooms, kitchens or cupboards.", "Activity around damp, paper, stored fabrics or food areas.", "Repeated sightings in warm or humid spaces."], process: [["Report the rooms", "Share where insects are seen and whether dampness or storage conditions may be relevant."], ["Discuss property conditions", "Affected areas, access and the extent of activity guide the treatment discussion."], ["Confirm treatment", "The service scope and final price are confirmed before booking."]], price: "A property-specific quote is confirmed before booking.", priceFactors: ["Number of rooms and extent of activity.", "Dampness, storage conditions and access.", "Treatment method and follow-up requirements."], prevention: ["Improve ventilation and address moisture sources where possible.", "Keep paper, fabrics and dry goods in sealed storage.", "Reduce clutter in cupboards and damp-prone areas."], faqs: [{ question: "Where do silverfish live?", answer: "They are often reported in humid or sheltered areas such as bathrooms, kitchens, cupboards and storage spaces." }, { question: "Are silverfish linked to damp?", answer: "Moisture and humidity can make a property more suitable for silverfish, so these conditions are useful to mention." }, { question: "What affects treatment cost?", answer: "Affected rooms, extent of activity, access and property conditions affect the final quote." }] }),
  "pest-control-services/moth-treatment": page({ title: "Moth Treatment", description: "Moth treatment in London for homes and rental properties. Describe moth activity or fabric damage for a property-specific service discussion.", summary: "Moths, larvae, shed cases or damage to natural fabrics and stored items may need a targeted property review.", signsTitle: "Possible signs of moth activity", signs: ["Small moths, larvae or cases in wardrobes, carpets or stored textiles.", "Holes or thinning in natural-fibre garments, rugs or upholstery.", "Activity in dark storage areas or around rarely moved furnishings."], process: [["Describe items and rooms", "Tell us which textiles, furnishings or storage areas are affected."], ["Review the extent", "The materials, rooms and accessibility inform the treatment discussion."], ["Confirm the scope", "We confirm the price and any preparation requirements before booking."]], price: "A property-specific quote is confirmed before booking.", priceFactors: ["Affected textiles, carpets or furnishings.", "Number of rooms and storage areas.", "Preparation, access and treatment requirements."], prevention: ["Clean and inspect stored natural-fibre items regularly.", "Vacuum carpets, rugs and wardrobe edges.", "Store clean seasonal clothing in sealed containers."], faqs: [{ question: "How can I tell if moths are damaging fabrics?", answer: "Larvae, cases, holes and thinning in natural fibres can be signs. Share photos or details through the contact route if requested." }, { question: "Can moths affect carpets?", answer: "Some moth activity can involve natural-fibre carpets and rugs. Mention the material and affected area when contacting us." }, { question: "What affects treatment price?", answer: "The number of rooms, affected materials, accessibility and required treatment affect the final quote." }] }),
  "pest-control-services/carpet-beetles": page({ title: "Carpet Beetle Treatment", description: "Carpet beetle treatment in London for homes and rental properties. Report larvae, shed skins or fabric damage for a tailored service discussion.", summary: "Carpet beetle larvae may be found near carpets, skirting, wardrobes and natural fibres. Explain what you have found and where.", signsTitle: "Possible signs of carpet beetles", signs: ["Small hairy larvae or shed skins near carpets and skirting.", "Damage to natural-fibre textiles, stored clothing or upholstery.", "Activity in quiet, dark edges of rooms or cupboards."], process: [["Identify affected areas", "Tell us where larvae, skins or damage have been noticed."], ["Review material and access", "Room layout, textiles and accessible edges help shape the service discussion."], ["Confirm the treatment", "The final scope, price and preparation requirements are agreed before booking."]], price: "A property-specific quote is confirmed before booking.", priceFactors: ["Affected rooms, carpets and furnishings.", "Extent of larvae or fabric damage.", "Preparation and treatment access."], prevention: ["Vacuum carpet edges, skirting and storage areas frequently.", "Clean and inspect natural-fibre items before storing them.", "Remove accumulated lint, hair and dust from quiet corners."], faqs: [{ question: "What do carpet beetle larvae look like?", answer: "They are often described as small, bristly larvae or shed skins near carpets, skirting and natural-fibre items." }, { question: "Can carpet beetles damage clothing?", answer: "Larvae can damage some natural-fibre textiles. Mention the materials and locations affected." }, { question: "How is pricing decided?", answer: "Affected areas, furnishings, accessibility and the required treatment determine the final quote." }] }),
  "pest-control-services/woodworm-treatment": page({ title: "Woodworm Treatment", description: "Woodworm treatment in London for properties with suspected timber damage. Describe the timber, holes and dust for a property-specific assessment.", summary: "Small holes and fresh-looking dust in timber can require a careful discussion of the affected material, location and condition.", signsTitle: "Possible signs of woodworm", signs: ["Small round holes in exposed timber or furniture.", "Fresh dust-like frass near holes or beneath timber.", "Damage or weakness in floorboards, roof timbers or furniture."], process: [["Describe the timber", "Tell us the location, type of timber, visible holes and whether fresh dust is present."], ["Review access and condition", "Affected structure, access and evidence of activity determine the assessment discussion."], ["Confirm scope", "Any inspection, treatment scope and final price are agreed before booking."]], price: "A property-specific quote is confirmed before booking.", priceFactors: ["Location and accessibility of timber.", "Evidence of active activity and extent of damage.", "Whether structural assessment or additional treatment is needed."], prevention: ["Keep timber areas ventilated and address persistent dampness.", "Avoid covering or painting affected timber before it is reviewed.", "Record the location of holes or fresh dust for discussion."], faqs: [{ question: "How do I know if woodworm is active?", answer: "Fresh frass near holes can be a useful sign, but activity and treatment needs should be assessed from the property details." }, { question: "Can woodworm affect structural timber?", answer: "It can affect different timber elements. Mention whether the concern is furniture, floorboards, loft timber or another area." }, { question: "What affects the price?", answer: "Timber location, access, evidence of activity and treatment scope determine the final quote." }] }),
  "pest-control-services/general-fogging": page({ title: "General Fogging", description: "General fogging in London for suitable pest-control situations. Property, pest concern and treatment suitability are reviewed before booking.", summary: "Fogging is not automatically appropriate for every pest issue. Describe the problem, affected spaces and property use so suitability can be discussed.", signsTitle: "Information needed before fogging", signs: ["The pest concern or signs observed.", "Rooms affected and the people, pets or business activity using them.", "Any ventilation, access or preparation constraints."], process: [["Describe the concern", "Tell us the pest issue, affected areas and property type."], ["Assess suitability", "The treatment method and preparation requirements are discussed before a service is offered."], ["Confirm the arrangement", "The final scope, price and aftercare information are confirmed before booking."]], price: "A property-specific quote is confirmed before booking.", priceFactors: ["Pest type and whether fogging is appropriate.", "Property size, rooms and preparation needs.", "Access, ventilation and any follow-up required."], prevention: ["Do not use unapproved products in occupied spaces.", "Follow any agreed preparation and re-entry guidance exactly.", "Address food, waste, moisture or access factors linked to the pest issue."], faqs: [{ question: "Is fogging suitable for every pest problem?", answer: "No. The pest type, property use and treatment requirements must be reviewed before fogging is considered." }, { question: "What preparation is needed?", answer: "Preparation depends on the property and agreed method. Instructions should be confirmed before any booking." }, { question: "How is the price set?", answer: "Suitability, property size, affected rooms, access and the required treatment determine the final quote." }] }),
  "pest-control-services/dead-pest-removal": page({ title: "Dead Pest Removal", description: "Dead pest removal in London for homes and properties. Describe the location, pest if known and safe access for a property-specific arrangement.", summary: "If a dead pest needs removing, provide the location, the pest type if known and any access restrictions without handling it unnecessarily.", signsTitle: "Details to share", signs: ["Where the animal or pest is located.", "Whether it is indoors, outdoors, in a loft or another restricted area.", "Any odour, contamination concern or access limitation."], process: [["Describe the location", "Tell us where the pest is and whether it can be safely accessed."], ["Review the arrangement", "Property access, disposal requirements and any associated pest concern are discussed."], ["Confirm service", "The final price and suitable arrangement are confirmed before booking."]], price: "A property-specific quote is confirmed before booking.", priceFactors: ["Location and access difficulty.", "Pest type and condition if known.", "Any sanitation or follow-up requirements."], prevention: ["Avoid direct contact and keep children and pets away.", "Do not disturb an inaccessible carcass in a void or roof area.", "Report recurring activity so the underlying issue can be discussed."], faqs: [{ question: "Can you remove a dead pest from a loft?", answer: "Tell us the exact location and access available so suitability can be reviewed before booking." }, { question: "Should I handle a dead animal myself?", answer: "Avoid unnecessary direct handling. Explain the location and condition so the appropriate arrangement can be discussed." }, { question: "Does removal address the original pest issue?", answer: "Removal and the underlying cause can be discussed separately; describe any recurring signs or entry points." }] }),
  "pest-control-services/pest-inspection": page({ title: "Pest Inspection", description: "Pest inspections in London for properties with unexplained pest signs. Describe activity, affected areas and property type for a tailored review.", summary: "When the pest type or extent of a problem is unclear, an inspection discussion can start with the signs, rooms and timing you have observed.", signsTitle: "When an inspection may be useful", signs: ["Unidentified droppings, damage, noises or insects.", "Signs appearing in several parts of the property.", "A recurring problem where the likely entry point is unclear."], process: [["Share the evidence", "Describe signs, affected rooms and when activity occurs."], ["Discuss inspection needs", "Property layout, access and the information available help determine the next step."], ["Confirm the visit", "Any inspection scope, quote and follow-on work are discussed before booking."]], price: "A property-specific quote is confirmed before booking.", priceFactors: ["Property size and number of areas to inspect.", "Access to lofts, voids, external spaces or commercial areas.", "Whether follow-on treatment is required."], prevention: ["Keep a short record of sightings, dates and affected areas.", "Avoid disturbing signs before they can be discussed.", "Make safe access details available when contacting us."], faqs: [{ question: "Can I book an inspection if I do not know the pest?", answer: "Yes. Describe the signs and affected areas rather than guessing the pest type." }, { question: "What should I note before an inspection?", answer: "Useful details include sightings, noises, droppings, damage, locations, timing and access limitations." }, { question: "Does an inspection include treatment?", answer: "Any follow-on service depends on the findings and must be discussed and confirmed separately." }] }),
  // NOTE: no advertised starting price — commercial contracts aren't launched yet.
  // The previous "From £49/month" figure was a copy-paste of the unrelated Best One
  // Club loyalty subscription price and did not reflect a real commercial rate.
  "pest-control-services/commercial-pest-control": page({ title: "Commercial Pest Control", description: "Commercial pest control in London for business premises. Service requirements and a custom quote confirmed after discussing your site.", summary: "Businesses can describe their premises, pest concerns, operational hours and access needs so an appropriate service arrangement can be discussed.", signsTitle: "Commercial information to provide", signs: ["Premises type and operating hours.", "Pest signs, affected areas and any food-handling or public-facing spaces.", "Site access, contact arrangements and recurring concerns."], process: [["Describe the premises", "Tell us the business type, property layout, affected areas and operational constraints."], ["Review service requirements", "The pest concern, access and monitoring or visit needs guide the discussion."], ["Confirm the arrangement", "We confirm scope, frequency, final price and reporting requirements before booking."]], price: "Custom quote confirmed after discussing your premises.", priceFactors: ["Premises type, size and operating hours.", "Pest risk, affected areas and visit frequency.", "Monitoring, reporting and access requirements."], prevention: ["Maintain waste, food-storage and cleaning controls appropriate to the premises.", "Record sightings and locations for the responsible site contact.", "Keep service and delivery areas accessible for inspection."], faqs: [{ question: "What businesses can request commercial pest control?", answer: "Businesses can describe their premises and requirements; suitability is confirmed based on the actual site and service needs." }, { question: "How much does commercial pest control cost?", answer: "Commercial pest control is quoted per site once premises, risk, visit frequency and scope are confirmed — there is no fixed starting rate yet." }, { question: "Can visits be planned around trading hours?", answer: "Share operating hours and access requirements so a suitable arrangement can be discussed before booking." }] }),
} as const;

export type ApprovedServiceKey = keyof typeof approvedServicePages;

const pestPage = (title: string, description: string, summary: string, signsTitle: string, signs: readonly string[], price: string, priceFactors: readonly string[], prevention: readonly string[]) => page({
  title,
  description,
  summary,
  signsTitle,
  signs,
  process: [["Describe what you have noticed", `Tell us the signs, affected areas and when the ${title.toLowerCase()} concern began.`], ["Review the property", "Access, affected areas and the extent of activity are reviewed to discuss the appropriate approach."], ["Confirm the arrangement", "The full price and any follow-up visits are confirmed before booking."]],
  price,
  priceFactors,
  prevention,
  faqs: [{ question: `What are signs I need ${title.toLowerCase()}?`, answer: `${signs[0]} Describe what you have seen so the right next step can be discussed.` }, { question: `How much does ${title.toLowerCase()} cost?`, answer: `${price} The final quote depends on the property, extent of activity, access and any follow-up needs.` }, { question: `Can ${title.toLowerCase()} need more than one visit?`, answer: "It may. The need for further visits depends on the situation and is confirmed before booking." }],
});

export const approvedPestExtensionPages = {
  "pest-control-services/pharaoh-ant-control": pestPage("Pharaoh Ant Control", "Pharaoh ant control in London for homes and commercial premises. Property-specific quote confirmed before booking.", "Pharaoh ants form small trailing colonies that split when disturbed, so a careful approach matters. Describe where trails are seen.", "Possible signs of pharaoh ants", ["Fine trails of very small pale ants near warmth, moisture or food.", "Activity spreading between rooms in commercial or multi-occupancy buildings.", "Trails persisting despite general cleaning."], "A property-specific quote is confirmed before booking.", ["Extent of activity and number of affected rooms.", "Property type, especially multi-occupancy or commercial sites.", "Access and the treatment approach required."], ["Avoid disturbing trails or using shop sprays, which can split colonies further.", "Report activity promptly in healthcare or commercial food settings.", "Keep food sealed and surfaces clean while advice is sought."]),
  "pest-control-services/bed-bug-heat-treatment": pestPage("Bed Bug Heat Treatment", "Bed bug heat treatment in London for homes and rental properties. Property-specific quote confirmed before booking.", "Heat treatment can be discussed as an alternative to chemical treatment for suitable properties and bed bug infestations.", "When heat treatment may be discussed", ["Confirmed bed bug activity in a room or property.", "A preference to avoid chemical treatment where suitable.", "Furnishings and room layout that can accommodate the equipment used."], "A property-specific quote is confirmed before booking.", ["Room size and number of rooms treated.", "Furnishings, electronics and items requiring preparation or removal.", "Access and power requirements for treatment equipment."], ["Follow all preparation guidance provided before the appointment.", "Remove heat-sensitive items as instructed in advance.", "Keep treated rooms accessible and undisturbed during the process."]),
  "pest-control-services/bed-bug-mattress-protection": pestPage("Bed Bug Mattress Protection", "Bed bug mattress encasement and protection in London. Property-specific quote confirmed before booking.", "Mattress and bed frame protection can be discussed alongside treatment or as a preventative step for at-risk properties.", "When mattress protection may help", ["Bed bug treatment has been carried out and ongoing protection is wanted.", "A property is at higher risk, such as rented or multi-occupancy accommodation.", "Mattresses or bed frames need encasing to limit future activity."], "A property-specific quote is confirmed before booking.", ["Number and size of mattresses or bed frames.", "Whether protection follows an active treatment.", "Access to bedrooms and furniture removal if required."], ["Use encasements rated for bed bug exclusion.", "Inspect bedding and frames regularly for early signs of activity.", "Check second-hand beds and furniture before bringing them into the property."]),
  "pest-control-services/bee-removal": pestPage("Bee Removal", "Bee removal and relocation in London. Property-specific quote confirmed before booking, with wildlife protections considered.", "Bees are protected pollinators, so removal is approached carefully with relocation preferred over destruction where possible.", "Possible signs of a bee presence", ["A visible swarm or nest in a wall cavity, roof space or garden feature.", "Repeated bee activity around one entry point.", "Concern around entrances, gardens or areas used by children or pets."], "A property-specific quote is confirmed before booking.", ["Nest location, height and accessibility.", "Whether a swarm or an established nest is present.", "Any relocation or specialist handling required."], ["Do not block an active entrance or disturb the nest.", "Keep people and pets away from the affected area.", "Report swarms promptly so options can be discussed."]),
  "pest-control-services/bee-nest-extraction": pestPage("Bee Nest Extraction", "Bee nest extraction in London for established nests in structures. Property-specific quote confirmed before booking.", "An established bee nest inside a wall, chimney or roof void needs a careful, structure-specific extraction discussion.", "When nest extraction may be needed", ["A nest has been present for some time inside a wall, chimney or roof void.", "Comb, honey or activity is affecting the structure.", "Simple removal is not possible due to the nest location."], "A property-specific quote is confirmed before booking.", ["Nest location within the structure and access required.", "Extent of comb and whether remedial building work is needed.", "Height, access equipment and time required."], ["Avoid attempting extraction yourself given the structural access involved.", "Report staining, smells or renewed activity after any previous treatment.", "Keep the area away from foot traffic until assessed."]),
  "pest-control-services/bird-control": pestPage("Bird Control", "Bird control in London for homes and commercial premises. Property-specific quote confirmed before booking.", "Nesting, fouling or roosting birds on a property can be discussed alongside the building type, access and affected areas.", "Possible signs needing bird control", ["Nesting or roosting on ledges, roofs or signage.", "Fouling affecting walkways, stock or building surfaces.", "Noise or blocked guttering linked to bird activity."], "A property-specific quote is confirmed before booking.", ["Building height, access and the areas affected.", "Bird species and any relevant seasonal or legal considerations.", "Scale of fouling or nesting material to be addressed."], ["Avoid disturbing active nests, which may be protected during nesting season.", "Keep affected areas clean and dry where safely possible.", "Report recurring roosting spots for a tailored discussion."]),
  "pest-control-services/pigeon-control": pestPage("Pigeon Control / Removal", "Pigeon control in London for homes, roofs and commercial premises. Property-specific quote confirmed before booking.", "Pigeon fouling, nesting and roosting can be discussed around the building, ledges and access involved.", "Possible signs of pigeon activity", ["Fouling on ledges, roofs, balconies or walkways.", "Nesting material in gutters, vents or roof voids.", "Regular roosting on signage, ledges or external units."], "A property-specific quote is confirmed before booking.", ["Building height, ledges and roosting locations.", "Extent of fouling and nesting material present.", "Access equipment and safe working requirements."], ["Avoid disturbing active nests without advice.", "Clean fouling carefully using appropriate protection.", "Report recurring roosting spots so proofing can be discussed."]),
  "pest-control-services/bird-pigeon-proofing": pestPage("Bird & Pigeon Proofing", "Bird and pigeon proofing in London using netting, spiking or wire systems. Property-specific quote confirmed before booking.", "Proofing measures such as netting, spikes or wires can be discussed once the ledges, roofline and building material are known.", "When proofing may be discussed", ["Recurring roosting or nesting on the same ledges or roofline.", "A building with multiple access points for birds.", "A preventative measure wanted after previous bird activity."], "A property-specific quote is confirmed before booking.", ["Building height, ledge length and roofline design.", "Proofing method suited to the structure and material.", "Access equipment and installation time required."], ["Keep ledges clear of nesting material before installation.", "Maintain proofing systems and check for gaps periodically.", "Report any damage to installed proofing promptly."]),
  "pest-control-services/falconry-bird-control": pestPage("Falconry Bird Control", "Falconry-based bird deterrent services in London for sites with persistent bird activity. Property-specific quote confirmed before booking.", "Trained birds of prey can be discussed as a deterrent for sites with ongoing gull, pigeon or corvid activity.", "When falconry deterrence may be discussed", ["Persistent bird activity affecting a large site or building.", "Other proofing methods have not resolved the issue.", "A site needs a visible, ongoing deterrent presence."], "A property-specific quote is confirmed before booking.", ["Site size and the bird species involved.", "Frequency and duration of deterrent visits.", "Access and any site-specific scheduling needs."], ["Combine deterrence with proofing where appropriate.", "Maintain a consistent visit schedule for lasting effect.", "Report changes in bird behaviour or new activity."]),
  "pest-control-services/solar-panel-bird-proofing": pestPage("Solar Panel Bird/Pigeon Proofing", "Solar panel bird and pigeon proofing in London to stop nesting beneath panels. Property-specific quote confirmed before booking.", "Birds nesting beneath solar panels can cause fouling, blockages and fire risk from nesting material, so proofing is discussed for the panel array.", "Possible signs under solar panels", ["Birds seen entering or leaving the gap beneath panels.", "Nesting material, fouling or noise from beneath the array.", "Previous nesting seasons under the same panels."], "A property-specific quote is confirmed before booking.", ["Roof height, pitch and panel array size.", "Access equipment required for the roof.", "Extent of existing nesting material to clear first."], ["Avoid disturbing active nests beneath panels without advice.", "Arrange proofing outside of nesting season where possible.", "Check for renewed activity each season."]),
  "pest-control-services/chimney-protection": pestPage("Chimney Protection", "Chimney bird and pest guard installation in London to stop nesting and blockages. Property-specific quote confirmed before booking.", "A chimney guard or cowl can be discussed to stop birds, squirrels or debris entering an unused or active chimney.", "When chimney protection may help", ["Birds or animals repeatedly entering an open chimney.", "Nesting material found in the flue or fireplace.", "A chimney no longer in active use that needs sealing against entry."], "A property-specific quote is confirmed before booking.", ["Chimney height, access and roof pitch.", "Whether the chimney is in active use.", "Guard or cowl type suited to the flue."], ["Do not seal a flue that is still in active use without proper advice.", "Have chimneys checked before the colder months.", "Report scratching or nesting sounds promptly."]),
  "pest-control-services/cluster-fly-control": pestPage("Cluster Fly Control", "Cluster fly control in London for properties with seasonal fly activity in roof spaces. Property-specific quote confirmed before booking.", "Cluster flies gathering in lofts, window reveals or roof voids, particularly in autumn, can be discussed for a targeted treatment.", "Possible signs of cluster flies", ["Groups of sluggish flies gathering at windows or in lofts.", "Seasonal activity, often noticeable in autumn and spring.", "Flies found in roof voids or unused rooms."], "A property-specific quote is confirmed before booking.", ["Loft or roof void access.", "Extent and seasonal timing of activity.", "Property size and number of affected rooms."], ["Vacuum clusters rather than crushing them where possible.", "Check loft access points for gaps allowing entry.", "Report recurring seasonal activity for a targeted visit."]),
  "pest-control-services/fly-control": pestPage("Fly Control", "Fly control in London for homes and commercial premises. Property-specific quote confirmed before booking.", "Persistent fly activity around food areas, waste or drains can be discussed alongside the property type and affected spaces.", "Possible signs needing fly control", ["Recurring flies around kitchens, bins or food preparation areas.", "Activity linked to drains, waste storage or outdoor areas.", "Fly presence affecting a commercial food or hospitality space."], "A property-specific quote is confirmed before booking.", ["Property type, especially food-handling premises.", "Source of activity, such as drains, waste or produce.", "Extent of activity and treatment required."], ["Keep waste covered and removed regularly.", "Clean drains and food areas to reduce breeding sites.", "Report recurring activity linked to a specific source."]),
  "pest-control-services/electric-fly-killer-services": pestPage("Electric Fly Killer (EFK) Services", "Electric fly killer supply, installation and servicing in London for commercial premises. Property-specific quote confirmed before booking.", "EFK units for kitchens and food premises can be discussed for installation, replacement tubes or ongoing servicing.", "When EFK services may be discussed", ["A commercial kitchen or food area needs fly control units installed.", "Existing units need servicing or replacement tubes.", "Compliance requirements call for a maintained EFK schedule."], "A property-specific quote is confirmed before booking.", ["Number of units and premises size.", "Installation, servicing or replacement scope.", "Visit frequency required for compliance."], ["Keep units clear of stock and food preparation splashback.", "Schedule regular servicing to maintain effectiveness.", "Report reduced catch rates or unit faults promptly."]),
  "pest-control-services/fox-control": pestPage("Fox Control", "Fox deterrent and management advice in London for gardens and commercial sites. Property-specific quote confirmed before booking.", "Fox activity in gardens or around bins can be discussed alongside deterrent and exclusion measures suited to the property.", "Possible signs of fox activity", ["Foxes seen regularly in a garden or on a site at night.", "Damage to bins, planting or garden structures.", "Denning activity such as digging under sheds or decking."], "A property-specific quote is confirmed before booking.", ["Garden or site size and access points.", "Evidence of denning or repeated activity.", "Deterrent or exclusion measures required."], ["Secure food waste and remove accessible food sources.", "Block potential den sites such as gaps under decking.", "Avoid feeding foxes to reduce repeat visits."]),
  "pest-control-services/glis-glis-control": pestPage("Glis Glis / Edible Dormouse Control", "Glis glis (edible dormouse) control in London, mainly in Chilterns-adjacent and loft-affected properties. Property-specific quote confirmed before booking.", "Glis glis are a protected but locally controlled species found in lofts and cavity walls, so a careful, property-specific approach is discussed.", "Possible signs of glis glis", ["Loud scratching or running noises in a loft, especially at night.", "Gnaw damage to timber, cabling or stored items in a loft.", "Sightings of a large, grey, squirrel-like animal with a bushy tail."], "A property-specific quote is confirmed before booking.", ["Loft access and extent of activity.", "Legal considerations affecting the control method used.", "Follow-up visits and exclusion work required."], ["Keep loft access available for assessment.", "Avoid attempting removal yourself given legal protections.", "Report noises promptly, particularly overnight activity."]),
  "pest-control-services/harlequin-ladybird-control": pestPage("Harlequin Ladybird Control", "Harlequin ladybird control in London for properties with large autumn clusters. Property-specific quote confirmed before booking.", "Large clusters of harlequin ladybirds gathering indoors in autumn can be discussed for removal and future prevention.", "Possible signs of harlequin ladybirds", ["Large clusters gathering on windows, walls or lofts in autumn.", "Ladybirds entering through small gaps around windows or eaves.", "Recurring seasonal clusters year after year."], "A property-specific quote is confirmed before booking.", ["Extent and location of clusters.", "Property size and entry points involved.", "Seasonal timing of the treatment."], ["Vacuum clusters gently rather than crushing them.", "Seal small gaps around windows and eaves where practical.", "Report recurring seasonal clustering for a targeted visit."]),
  "pest-control-services/mite-plaster-beetle-control": pestPage("Mite / Plaster Beetle Control", "Mite and plaster beetle control in London, common in new or recently plastered properties. Property-specific quote confirmed before booking.", "Tiny mites or plaster beetles appearing in new-build or freshly plastered rooms are often linked to residual damp and can be discussed for treatment.", "Possible signs of mites or plaster beetles", ["Tiny insects appearing on walls or windowsills in new or replastered rooms.", "Activity linked to recent building or plastering work.", "Recurrence while walls are still drying out."], "A property-specific quote is confirmed before booking.", ["Extent of activity and number of affected rooms.", "Whether recent plastering or building work has occurred.", "Ventilation and drying conditions in the property."], ["Improve ventilation to help walls dry out fully.", "Avoid excess moisture in newly plastered rooms.", "Report activity that continues once walls have dried."]),
  "pest-control-services/mole-control": pestPage("Mole Control", "Mole control in London for gardens, lawns and grounds. Property-specific quote confirmed before booking.", "Molehills and ridges appearing across a lawn or grounds can be discussed for a tailored control approach.", "Possible signs of mole activity", ["Molehills appearing across a lawn or garden.", "Raised ridges of soil beneath the surface.", "Repeated activity across a wide grassed area or grounds."], "A property-specific quote is confirmed before booking.", ["Size of the lawn or grounds affected.", "Extent and spread of molehills or ridges.", "Access for equipment across the grounds."], ["Avoid flattening molehills until the extent of activity is assessed.", "Note the pattern and spread of ridges for discussion.", "Keep grounds accessible for treatment equipment."]),
  "pest-control-services/rat-sewer-control": pestPage("Rat Sewer Control", "Rat sewer control and drainage-related rat treatment in London. Property-specific quote confirmed before booking.", "Rat activity linked to drains or sewer connections often needs a combined drainage and pest-control discussion.", "When sewer-related rat control may help", ["Rat activity appears linked to drains, manholes or sewer connections.", "Repeated rat problems despite surface-level treatment.", "Damaged or defective drainage suspected as an entry route."], "A property-specific quote is confirmed before booking.", ["Access to drains, manholes and external pipework.", "Whether a drain survey is needed alongside treatment.", "Extent of activity and repeat visits required."], ["Report suspected drain damage or defects promptly.", "Keep manhole covers secure and in good repair.", "Avoid disturbing drain covers without appropriate access."]),
  "pest-control-services/rabbit-control": pestPage("Rabbit Control", "Rabbit control in London for gardens, grounds and commercial sites. Property-specific quote confirmed before booking.", "Rabbit damage to lawns, planting or grounds can be discussed alongside fencing, exclusion and control options.", "Possible signs of rabbit activity", ["Burrows or warrens appearing in a garden or grounds.", "Damage to lawns, vegetable beds or young planting.", "Rabbits regularly seen on a site or grounds."], "A property-specific quote is confirmed before booking.", ["Size of grounds and extent of burrowing.", "Fencing or exclusion measures required.", "Access for equipment across the site."], ["Consider rabbit-proof fencing for vulnerable planting.", "Note the location and spread of burrows for discussion.", "Keep grounds accessible for assessment."]),
  "pest-control-services/slug-control": pestPage("Slug Control", "Slug control in London for gardens and vulnerable planting. Property-specific quote confirmed before booking.", "Heavy slug activity damaging planting or entering ground-floor rooms can be discussed for a tailored approach.", "Possible signs of slug activity", ["Damage to seedlings, vegetables or bedding plants.", "Slime trails across paths, patios or ground-floor floors.", "Slugs entering a property through gaps or door thresholds."], "A property-specific quote is confirmed before booking.", ["Garden size and extent of planting affected.", "Whether activity extends indoors through entry points.", "Treatment method suited to the outdoor space."], ["Reduce damp hiding spots such as thick mulch near doors.", "Check door thresholds and gaps for entry points.", "Report activity entering the property rather than just the garden."]),
  "pest-control-services/hornet-nest-removal": pestPage("Hornet Nest Removal", "Hornet nest removal in London, treated with additional care given hornet size and sting risk. Property-specific quote confirmed before booking.", "A hornet nest should be reported from a safe distance, since hornets can be more defensive than common wasps.", "Possible signs of a hornet nest", ["A large, papery nest, often larger than a typical wasp nest.", "Large flying insects seen repeatedly entering one gap or tree cavity.", "Activity noticeably more aggressive when the nest area is approached."], "A property-specific quote is confirmed before booking.", ["Nest location, height and access conditions.", "Proximity to occupied areas, paths or seating.", "Any additional safety measures required for removal."], ["Keep well away from an active hornet nest.", "Do not attempt removal yourself.", "Seek urgent medical help for signs of a severe allergic reaction."]),
  "pest-control-services/woodlice-control": pestPage("Woodlice Control", "Woodlice control in London for homes with damp-linked woodlice activity. Property-specific quote confirmed before booking.", "Large numbers of woodlice indoors are often linked to damp, so treatment is discussed alongside the affected areas and moisture sources.", "Possible signs of woodlice activity", ["Woodlice found in bathrooms, kitchens or damp cupboards.", "Activity linked to skirting, airbricks or damp external walls.", "Numbers increasing during wetter periods of the year."], "A property-specific quote is confirmed before booking.", ["Extent of activity and number of affected rooms.", "Damp conditions and likely entry points.", "Ventilation and moisture control required alongside treatment."], ["Improve ventilation in damp-prone rooms.", "Check airbricks and external walls for blockages.", "Address any underlying damp where possible."]),
  "pest-control-services/rodent-proofing": pestPage("Rat, Mice, Squirrel & Glis Glis Proofing", "Rodent-proofing works in London to seal entry points after rat, mice, squirrel or glis glis treatment. Property-specific quote confirmed before booking.", "Proofing external entry points helps reduce repeat rodent activity once the current issue has been addressed.", "When proofing may be discussed", ["Rodent treatment has identified likely entry points.", "Repeated activity despite previous treatment.", "A preventative measure wanted for an at-risk property."], "A property-specific quote is confirmed before booking.", ["Number and location of entry points to seal.", "Materials required for the property type.", "Access for proofing works across the building."], ["Keep entry points visible and unblocked until assessed.", "Report new gaps appearing around pipework or eaves.", "Combine proofing with ongoing monitoring where recommended."]),
  "pest-control-services/drain-sewer-camera-surveys": pestPage("Drain & Sewer Camera Surveys", "Drain and sewer camera surveys in London to identify defects linked to rat activity or blockages. Property-specific quote confirmed before booking.", "A camera survey can be discussed when drain defects are suspected as a cause of recurring rat activity or blockages.", "When a camera survey may help", ["Recurring rat activity suspected to be linked to drains.", "Unexplained blockages or slow drainage.", "A defect suspected but not visible from the surface."], "A property-specific quote is confirmed before booking.", ["Length and accessibility of the drain run.", "Number of access points available.", "Whether repair work follows the survey findings."], ["Report recurring blockages or drainage issues promptly.", "Keep manhole covers accessible for the survey.", "Address any identified defects to reduce repeat problems."]),
  "pest-control-services/disinfectant-biocide-treatment": pestPage("Disinfectant / Biocide Treatment", "Disinfectant and biocide treatment in London following pest activity or contamination concerns. Property-specific quote confirmed before booking.", "Areas affected by pest activity, droppings or contamination can be discussed for a disinfectant or biocide treatment alongside any pest control.", "When disinfectant treatment may help", ["Areas affected by droppings, nesting material or contamination.", "A property needing treatment after pest activity is addressed.", "Commercial or communal areas requiring hygiene treatment."], "A property-specific quote is confirmed before booking.", ["Extent and location of affected areas.", "Whether treatment follows active pest control work.", "Access and any preparation required before treatment."], ["Avoid disturbing contaminated areas without protection.", "Ventilate treated areas as advised afterwards.", "Report ongoing odour or contamination concerns."]),
  "pest-control-services/loft-insulation-removal-installation": pestPage("Loft Insulation Removal & Installation", "Loft insulation removal and replacement in London following rodent or bird contamination. Property-specific quote confirmed before booking.", "Contaminated or damaged loft insulation following pest activity can be discussed for removal and replacement alongside any proofing work.", "When insulation removal may be needed", ["Insulation contaminated by droppings, urine or nesting material.", "Insulation damaged or displaced by rodent or bird activity.", "Replacement wanted alongside proofing after treatment."], "A property-specific quote is confirmed before booking.", ["Loft size and extent of contaminated material.", "Access to the loft space.", "Whether proofing work is carried out alongside replacement."], ["Avoid disturbing contaminated insulation without protection.", "Report visible contamination or damage promptly.", "Combine replacement with proofing where recommended."]),
  "pest-control-services/pest-control-contracts": pestPage("Pest Control Contracts / Ongoing Pest Management", "Ongoing pest control contracts in London for residential blocks, landlords and businesses. Property-specific quote confirmed before booking.", "Ongoing contracted visits can be discussed for sites needing regular monitoring rather than a single one-off treatment.", "When an ongoing contract may help", ["A site with recurring pest risk needing regular monitoring.", "Landlords or managing agents responsible for multiple units.", "Compliance or reporting requirements for scheduled visits."], "A property-specific quote is confirmed before booking.", ["Site size, number of units and visit frequency.", "Monitoring, reporting and access requirements.", "Whether existing pest issues need addressing before the contract starts."], ["Maintain waste and hygiene standards between visits.", "Report new activity promptly rather than waiting for the next visit.", "Keep site access consistent for scheduled visits."]),
} as const;

const cleaningPage = (title: string, summary: string, focus: string, preparation: string, priceFactor: string) => page({
  title,
  description: `${title} in London from Bestone Services Ltd. Discuss the property, service scope and final price before booking.`,
  summary,
  signsTitle: "When this service may help",
  signs: [focus, `Tell us about the property, access and the areas that need attention.`, "Share a preferred date so the service arrangement can be discussed."],
  process: [["Share the relevant details", `Explain the property, the areas involved and any timing or access requirements for ${title.toLowerCase()}.`], ["Confirm the scope", "The requested work, any preparation and the price factors can be discussed for the actual property."], ["Agree the booking", "We confirm the full price and service arrangement before work is booked."]],
  price: "A property-specific quote is confirmed before booking.",
  priceFactors: [priceFactor, "Property size, condition, access and requested add-ons.", "Parking, key collection, timing and any specialist requirements."],
  prevention: [preparation, "Make the agreed areas accessible before the visit.", "Share relevant access or parking information early."],
  faqs: [{ question: `What information is needed for ${title.toLowerCase()}?`, answer: "Tell us about the property, the affected areas or items, condition, access, postcode or area and preferred timing." }, { question: `How is the price for ${title.toLowerCase()} decided?`, answer: `The property, scope, condition, access and any specialist requirements determine the final quote. ${priceFactor}` }, { question: "Is the booking confirmed immediately?", answer: "No. The full price, availability and service arrangement are confirmed before work is booked." }],
});

export const approvedCleaningServicePages = {
  "cleaning-services/domestic-cleaning": cleaningPage("Domestic Cleaning", "Practical home cleaning can be discussed around the rooms, priorities and household access that apply to your property.", "A home needs a one-off or tailored clean across everyday living spaces.", "Clear personal items and identify any rooms that need particular attention.", "The number of rooms, condition and requested cleaning priorities affect the quote."),
  "cleaning-services/regular-cleaning": cleaningPage("Regular Cleaning", "For ongoing household cleaning, explain the preferred frequency, rooms and practical access details for a suitable discussion.", "A property needs recurring support for everyday cleaning tasks.", "Keep a simple list of recurring priorities for kitchens, bathrooms and shared spaces.", "Visit frequency, property size and the agreed recurring scope affect the quote."),
  "cleaning-services/one-off-cleaning-services": cleaningPage("One-off Cleaning Services", "A one-off clean can be arranged around a particular event, property change or set of rooms needing attention.", "A home needs focused cleaning without an ongoing schedule.", "List the rooms, surfaces or event-related priorities before contacting us.", "Property condition, scope and any time-sensitive requirements affect the quote."),
  "cleaning-services/after-builders-cleaning": cleaningPage("After Builders Cleaning", "Post-work cleaning can be discussed once the building work is complete and the areas, dust and access conditions are clear.", "Dust, residue and construction-related mess remain after building or decorating work.", "Ensure work is complete and identify any fragile finishes or restricted areas.", "The amount of residue, property size, access and specialist surface needs affect the quote."),
  "cleaning-services/carpet-cleaning": cleaningPage("Carpet Cleaning", "Carpet cleaning can be discussed for marked, high-traffic or move-out areas, with material and condition considered first.", "Carpets have marks, odours, high-traffic wear or need attention before handover.", "Point out stains, pet areas and the carpet material if known.", "Number of rooms, carpet material, staining and drying/access conditions affect the quote."),
  "cleaning-services/oven-cleaning-service": cleaningPage("Oven Cleaning Service", "Oven cleaning can be discussed for built-in or freestanding appliances, including the appliance type and level of residue.", "An oven has baked-on residue, grease or needs attention before a handover.", "Let the appliance cool and mention the model or range type if known.", "Appliance size, condition, removable parts and access affect the quote."),
  "cleaning-services/appliance-cleaning": cleaningPage("Appliance Cleaning", "Appliance cleaning can be discussed for the specific item, its condition and the accessible components requiring attention.", "A kitchen or household appliance needs detailed cleaning before use or property handover.", "Identify the appliance type and any areas of heavy residue or restricted access.", "Appliance type, size, condition and required disassembly or access affect the quote."),
  "cleaning-services/mattress-cleaning-service": cleaningPage("Mattress Cleaning Service", "Mattress cleaning can be discussed around the mattress size, material, staining and access within the property.", "A mattress needs freshening after spills, marks or general use.", "Tell us the mattress size, material and any marks or odours to consider.", "Mattress size, material, condition and access to the room affect the quote."),
  "cleaning-services/upholstery-cleaning": cleaningPage("Upholstery Cleaning", "Sofa, chair and other upholstery cleaning depends on fabric type, item size, staining and the space available for access.", "Upholstered furniture has marks, odours or high-use areas needing attention.", "Identify the fabric, item size and any known stains before contacting us.", "Fabric type, number of items, staining and access affect the quote."),
  "cleaning-services/window-cleaning": cleaningPage("Window Cleaning", "Window cleaning can be discussed for internal or external glass, property height, access and the number of windows.", "Windows need cleaning after weather, construction work or a property handover.", "Tell us whether cleaning is internal, external or both and describe access safely.", "Window count, height, access equipment and internal/external scope affect the quote."),
  "cleaning-services/holiday-rental-cleaning": cleaningPage("Holiday Rental Cleaning", "Holiday-rental cleaning can be planned around changeover dates, guest-ready priorities, linen arrangements and property access.", "A short-let property needs preparing between guests or before an arrival.", "Share turnover timing, property size and any linen or inventory priorities.", "Changeover timing, bedrooms, linen needs and property condition affect the quote."),
  "cleaning-services/range-cooker-cleaning": cleaningPage("Range Cooker Cleaning", "Range cooker cleaning can be discussed with the cooker type, size, fuel arrangement and accessible components in mind.", "A range cooker needs attention to ovens, hob areas or removable components.", "Tell us the range type and number of ovens or compartments if known.", "Cooker size, number of ovens, condition and access affect the quote."),
  "cleaning-services/aga-cleaning": cleaningPage("AGA Cleaning", "AGA cleaning requires the appliance type, condition and access arrangements to be discussed before a suitable scope is agreed.", "An AGA appliance needs specialist cleaning attention for its accessible areas.", "Identify the AGA model or configuration and any areas of concern.", "Model, condition, accessible components and required preparation affect the quote."),
  "cleaning-services/bbq-cleaning": cleaningPage("BBQ Cleaning", "BBQ cleaning can be discussed for the appliance size, fuel type, condition and outdoor access arrangements.", "A barbecue has grease, residue or seasonal build-up before use.", "Allow the barbecue to cool and identify its type and location.", "BBQ size, fuel type, residue level and outdoor access affect the quote."),
  "cleaning-services/curtains-and-blinds-cleaning": cleaningPage("Curtains and Blinds Cleaning", "Curtain and blind cleaning depends on material, installation, dimensions and whether removal or specialist handling is required.", "Window coverings show dust, marks or need cleaning as part of a property refresh.", "Tell us the type of curtain or blind, dimensions and any material information.", "Material, dimensions, quantity and removal/access requirements affect the quote."),
  "cleaning-services/leather-sofa-cleaning-services": cleaningPage("Leather Sofa Cleaning Services", "Leather sofa cleaning should account for leather type, condition, colouring and any marks before a cleaning approach is discussed.", "Leather seating has surface marks, dirt or wear that needs careful cleaning.", "Share the sofa size, leather type if known and the condition of affected areas.", "Leather type, item size, condition and specialist care requirements affect the quote."),
  "cleaning-services/conservatory-cleaning": cleaningPage("Conservatory Cleaning", "Conservatory cleaning can be discussed around glass, frames, flooring, height and the internal or external areas required.", "A conservatory needs seasonal cleaning or attention after weather and general use.", "Describe the glass, frames, roof access and any restricted areas safely.", "Size, glazing, height, access and internal/external scope affect the quote."),
  "cleaning-services/gutter-cleaning": cleaningPage("Gutter Cleaning", "Gutter cleaning requires a clear discussion of property height, gutter access, visible blockages and safe working conditions.", "Gutters show overflow, debris or blockages that need safe attention.", "Describe the property height, affected side and visible issue from ground level.", "Height, length, access, debris and safe working conditions affect the quote."),
  "cleaning-services/home-organising-services": cleaningPage("Home Organising Services", "Home organising can be discussed around rooms, storage goals, household priorities and the level of support wanted.", "A home needs help creating clearer, more practical storage and room systems.", "Identify the rooms, storage challenges and desired outcome before contacting us.", "Number of rooms, amount of belongings, goals and session requirements affect the quote."),
  "cleaning-services/laundry-dry-cleaning": cleaningPage("Laundry and Dry Cleaning", "Laundry and dry-cleaning requirements can be discussed around garment types, collection arrangements and any care-label restrictions.", "Garments, bedding or household textiles need cleaning with suitable handling.", "Check care labels and list delicate, stained or time-sensitive items.", "Item types, quantities, care requirements and collection/delivery arrangements affect the quote."),
} as const;

export const allApprovedServicePages: Record<string, ApprovedServicePage> = {
  ...approvedServicePages,
  ...approvedCleaningServicePages,
  ...approvedPestExtensionPages,
};
