import { serviceFaqSchema, type ServiceFaq } from "@/content/service-types";

type ApprovedServicePage = {
  title: string;
  description: string;
  summary: string;
  signsTitle: string;
  signs: readonly string[];
  process: readonly [string, string][];
  price: string;
  priceFactors: readonly string[];
  prevention: readonly string[];
  faqs: readonly ServiceFaq[];
};

const page = (data: Omit<ApprovedServicePage, "faqs"> & { faqs: readonly { question: string; answer: string }[] }) => ({ ...data, faqs: serviceFaqSchema.array().parse(data.faqs) });

export const approvedServicePages = {
  "cleaning-services/end-of-tenancy-cleaning": page({
    title: "End of Tenancy Cleaning",
    description: "End of tenancy cleaning in London for tenants, landlords and letting agents. Starting from £79; final scope and price confirmed before booking.",
    summary: "Prepare a rental property for key handover with a cleaning scope based on its size, condition, contents and any inspection priorities.",
    signsTitle: "When end of tenancy cleaning may help",
    signs: ["Keys are due back and the property needs preparing for handover.", "A landlord or agent has requested attention to kitchens, bathrooms or living spaces.", "The property is furnished, has access constraints or needs add-ons discussed before a date is agreed."],
    process: [["Share the property details", "Tell us the property type, bedroom count, condition, furniture status, postcode and preferred handover date."], ["Confirm the cleaning scope", "Discuss the rooms, access information and any priorities such as appliances, carpets or specific areas."], ["Agree the booking", "We confirm the full price and suitable arrangement before any work is booked."]],
    price: "Starting from £79 for a studio flat.",
    priceFactors: ["Bedroom count, property condition and furnished or unfurnished status.", "Appliances, carpets, upholstery or other requested add-ons.", "Access, parking, key collection and the timing of handover."],
    prevention: ["Keep an inspection checklist and note priorities before the cleaning date.", "Remove personal belongings where possible so agreed areas are accessible.", "Share key, parking and access details early to avoid delays."],
    faqs: [{ question: "What is included in end of tenancy cleaning?", answer: "The final scope depends on the property and confirmed requirements. Customers commonly discuss kitchens, bathrooms, bedrooms, living spaces, floors and accessible internal surfaces." }, { question: "How much does end of tenancy cleaning cost?", answer: "Standard studio cleaning starts from £79. The final price depends on property size, condition, access, contents and any requested add-ons, and is confirmed before booking." }, { question: "Can I arrange cleaning around key handover?", answer: "Yes. Share the preferred date and any key or access requirements when you contact us so the arrangement can be discussed." }],
  }),
  "pest-control-services/rat-control": page({
    title: "Rat Control", description: "Rat control in London for homes, rental properties and businesses. Starting from £109; treatment requirements are confirmed before booking.", summary: "If you have seen rats, droppings, gnaw marks or repeated activity, describe the affected areas so the right next step can be discussed.", signsTitle: "Possible signs of a rat problem", signs: ["Droppings, gnaw marks or damaged food packaging.", "Scratching or movement in lofts, walls, cupboards or under floors.", "Rats seen near bins, kitchens, gardens or building entry points."], process: [["Describe the activity", "Tell us where signs appear, when you first noticed them and whether the problem is indoors or outdoors."], ["Review the property factors", "Access, entry points, extent of activity and property use help determine the appropriate approach."], ["Confirm treatment and follow-up", "The full price and whether further visits may be needed are confirmed before booking."]], price: "Starting from £109.", priceFactors: ["Severity and spread of activity.", "Number of affected rooms or external areas.", "Access, likely entry points and whether further visits are needed."], prevention: ["Keep food sealed and remove accessible waste.", "Report gaps around pipes, doors and external openings for assessment.", "Avoid handling rodents or droppings without appropriate precautions."], faqs: [{ question: "What are common signs of rats?", answer: "Common signs include droppings, gnaw marks, noises in voids, damage to food packaging and sightings near waste or entry points." }, { question: "How much does rat control cost?", answer: "Rat control starts from £109 for standard cases. Severity, property access, affected areas and follow-up needs can change the final quote." }, { question: "Can rat treatment need more than one visit?", answer: "Yes. Further visits may be needed depending on the infestation and the treatment plan confirmed for the property." }],
  }),
  "pest-control-services/mice-control": page({
    title: "Mice Control", description: "Mice control in London for homes, rental properties and businesses. Starting from £99; final treatment requirements confirmed before booking.", summary: "Mice can be active in kitchens, cupboards, walls and storage areas. Explain what you have seen and where activity is occurring.", signsTitle: "Possible signs of mice", signs: ["Small droppings in cupboards, kitchens or storage areas.", "Scratching sounds in walls, ceilings or under floors.", "Chewed packaging, gaps around services or a persistent musky smell."], process: [["Report the signs", "Share the affected rooms, the timing of activity and any sightings or damage."], ["Assess the likely scope", "Property layout, access and signs of entry help shape the treatment discussion."], ["Arrange the agreed response", "The full price and any potential additional visits are confirmed before work is booked."]], price: "Starting from £99.", priceFactors: ["Number of rooms and the extent of activity.", "Likely entry points and access to them.", "Whether monitoring or follow-up visits are required."], prevention: ["Store dry food in sealed containers and clear crumbs promptly.", "Keep cupboards and service areas accessible for assessment.", "Note gaps around pipes or skirting so they can be discussed."], faqs: [{ question: "How do I know if I have mice?", answer: "Small droppings, scratching in voids, chewed packaging and sightings in kitchens or storage areas are common signs." }, { question: "How much does mice control cost?", answer: "Mice control starts from £99 for standard cases. The final quote depends on the property, extent of activity, access and follow-up needs." }, { question: "Will mice control require another visit?", answer: "It may. The need for further visits depends on the infestation and is discussed before booking." }],
  }),
  "pest-control-services/bed-bug-treatment": page({
    title: "Bed Bug Treatment", description: "Bed bug treatment in London for homes and rental properties. Starting from £149; treatment scope and visits confirmed before booking.", summary: "Bites, spotting around bedding and insects near beds or furniture can be stressful. Provide clear details without trying to diagnose the issue alone.", signsTitle: "Possible signs of bed bugs", signs: ["Small blood spots or dark marks on bedding, mattresses or bed frames.", "Bites noticed after sleeping, though bites alone do not confirm bed bugs.", "Live insects, shed skins or activity around beds, sofas or luggage."], process: [["Describe what you have noticed", "Tell us the rooms affected, signs found and when the concern began."], ["Discuss preparation and treatment", "The property layout, affected furnishings and treatment requirements are reviewed before a booking is agreed."], ["Confirm visits and aftercare", "We confirm the price, any preparation steps and whether more than one visit may be needed."]], price: "Starting from £149.", priceFactors: ["Number of affected rooms and furnishings.", "Evidence and extent of activity.", "Preparation requirements and any follow-up visits."], prevention: ["Avoid moving bedding or furniture between rooms before advice is given.", "Keep inspected items separate and follow agreed preparation guidance.", "Check luggage and second-hand furniture carefully after travel or purchase."], faqs: [{ question: "What are signs of bed bugs?", answer: "Possible signs include dark spotting, shed skins, live insects and activity around beds or upholstered furniture. Bites alone are not proof." }, { question: "How much does bed bug treatment cost?", answer: "Bed bug treatment starts from £149. The final quote depends on affected rooms, furnishings, preparation and the treatment plan." }, { question: "Can bed bug treatment require more than one visit?", answer: "Yes. Treatment may require more than one visit depending on the infestation and plan confirmed for the property." }],
  }),
  "pest-control-services/cockroach-control": page({
    title: "Cockroach Control", description: "Cockroach control in London for homes, rentals and business premises. Starting from £119; final treatment plan confirmed before booking.", summary: "Cockroaches are often noticed around kitchens, bathrooms, appliances and warm utility areas. Describe where and how often activity occurs.", signsTitle: "Possible signs of cockroaches", signs: ["Live insects seen in kitchens, bathrooms, cupboards or around appliances.", "Small dark droppings or egg cases in sheltered areas.", "Activity that is more noticeable at night or around food and moisture sources."], process: [["Report locations and timing", "Tell us which rooms are affected, when activity is seen and any evidence you have noticed."], ["Review the treatment needs", "Property use, affected areas, hygiene access and the level of activity inform the treatment discussion."], ["Confirm the plan", "We confirm the full quote, preparation requirements and potential need for follow-up before booking."]], price: "Starting from £119.", priceFactors: ["Extent of activity and number of affected spaces.", "Property type, food areas and access around appliances.", "Preparation, treatment method and additional visits."], prevention: ["Remove food residue and keep waste covered.", "Fix moisture issues where possible and keep sinks dry overnight.", "Avoid moving items from affected rooms until advice is provided."], faqs: [{ question: "Where are cockroaches commonly found?", answer: "They are often reported in kitchens, bathrooms, cupboards, utility areas and around appliances where food, warmth or moisture are present." }, { question: "How much does cockroach control cost?", answer: "Cockroach treatment starts from £119. Final cost depends on the extent of activity, affected areas, access and required follow-up." }, { question: "Can cockroach treatment need more than one visit?", answer: "Yes. Further treatment may be needed depending on the infestation and the plan confirmed for the property." }],
  }),
  "pest-control-services/ant-treatment": page({
    title: "Ant Treatment", description: "Ant treatment in London for homes, gardens and business premises. Starting from £69; final treatment requirements confirmed before booking.", summary: "Repeated ant trails in kitchens, entry points or outdoor areas can be disruptive. Explain where activity starts and where ants are travelling.", signsTitle: "When to consider ant treatment", signs: ["Visible trails around food, sinks, doors, windows or skirting.", "Recurring activity from a garden, patio, wall gap or other entry point.", "Ants appearing in multiple rooms or around a business food area."], process: [["Map the activity", "Tell us where ants have been seen, their travel route if known and when activity is most noticeable."], ["Consider the surroundings", "Indoor and outdoor areas, access and likely entry points are reviewed to discuss the appropriate treatment."], ["Confirm the visit", "We confirm the final quote and any relevant preparation or access details before booking."]], price: "Starting from £69.", priceFactors: ["Whether activity is indoors, outdoors or both.", "Number of affected rooms or entry areas.", "Access to likely trails, nests or entry points."], prevention: ["Wipe food spills and store food in sealed containers.", "Remove standing water and keep bins closed.", "Note recurring entry points so they can be discussed."], faqs: [{ question: "Why are ants coming into my property?", answer: "Ants may be attracted by food, water and shelter, often using small gaps around doors, windows, walls or service points." }, { question: "How much does ant treatment cost?", answer: "Ant treatment starts from £69 for standard cases. The final quote depends on affected locations, access and the treatment required." }, { question: "Can ants return after treatment?", answer: "New activity can occur if food sources or entry points remain available. Prevention guidance and property-specific advice can help reduce repeat activity." }],
  }),
  "pest-control-services/flea-treatment": page({
    title: "Flea Treatment", description: "Flea treatment in London for homes and rental properties. Starting from £89; property details and treatment requirements confirmed before booking.", summary: "Fleas can be noticed through bites, pet activity or movement in carpets and soft furnishings. Tell us which rooms and items are affected.", signsTitle: "Possible signs of fleas", signs: ["Bites noticed on people or pets, particularly around ankles or lower legs.", "Small insects seen in pet bedding, carpets, rugs or upholstery.", "Activity continuing after pets have been treated or areas cleaned."], process: [["Describe the affected areas", "Share the rooms, flooring, furnishings and pet-related details that may be relevant."], ["Review preparation", "The treatment discussion considers property size, soft furnishings and any preparation required."], ["Confirm the arrangement", "We confirm the price, treatment scope and any follow-up requirements before booking."]], price: "Starting from £89.", priceFactors: ["Number of rooms, carpets and soft furnishings.", "Pet areas and the extent of activity.", "Preparation and whether a further visit is required."], prevention: ["Follow veterinary advice for pets where relevant.", "Wash pet bedding and vacuum carpets and upholstery regularly.", "Empty vacuum contents safely after cleaning affected areas."], faqs: [{ question: "How do I know if I have fleas?", answer: "Possible signs include bites, flea activity around pets, or small insects in pet bedding, carpets and upholstery. Other causes are possible, so share the signs you have noticed." }, { question: "How much does flea treatment cost?", answer: "Flea treatment starts from £89. The final quote depends on property size, affected rooms, soft furnishings and the treatment plan." }, { question: "Do pets need separate care?", answer: "Pet health should be discussed with a qualified veterinary professional. Tell us about pets and their areas so treatment requirements can be considered." }],
  }),
  "pest-control-services/wasp-treatment": page({
    title: "Wasp Treatment", description: "Wasp treatment and nest removal in London. Starting from £59; location, access and final service scope confirmed before booking.", summary: "A visible nest or repeated wasp activity around a roofline, loft, garden or wall opening should be described from a safe distance.", signsTitle: "Possible signs of a wasp nest", signs: ["Repeated wasp flight to one gap, roofline, loft area, shed or wall opening.", "A visible papery nest in a sheltered location.", "Activity near entrances, outdoor seating or areas used by children or pets."], process: [["Tell us the nest location", "Describe where activity is happening, whether the nest is visible and how safely the area can be accessed."], ["Review access and risk", "Height, location, surrounding activity and property access inform the service discussion."], ["Confirm treatment", "The final price and suitable arrangement are confirmed before booking."]], price: "Starting from £59.", priceFactors: ["Nest location, height and access conditions.", "Whether the nest is visible and safely reachable.", "Property layout and any special access requirements."], prevention: ["Keep away from active nests and do not block the entrance.", "Keep food and drinks covered outdoors where wasps are active.", "Seek urgent medical help if someone has signs of a severe allergic reaction."], faqs: [{ question: "Should I remove a wasp nest myself?", answer: "Avoid disturbing, blocking or attempting to remove an active nest yourself. Describe the location from a safe distance so the appropriate next step can be discussed." }, { question: "How much does wasp treatment cost?", answer: "Wasp treatment starts from £59. The final quote depends on nest location, height, access and the treatment required." }, { question: "Can you help if the nest is in a loft or roofline?", answer: "Tell us where the activity is occurring and what access is available. Suitability and the arrangement can then be reviewed before booking." }],
  }),
} as const;

export type ApprovedServiceKey = keyof typeof approvedServicePages;
