export type ServiceCategory = "cleaning" | "pest-control" | "gardening" | "removals";
export type JobType = "one-off" | "recurring" | "inspection" | "emergency";
export type PropertySize = "studio" | "1-bed" | "2-bed" | "3-bed" | "4-plus" | "commercial";
export type Urgency = "emergency" | "this-week" | "flexible";

export interface DirectoryService {
  id: string;
  name: string;
  category: ServiceCategory;
  categoryLabel: string;
  subService: string;
  jobTypes: JobType[];
  propertySizes?: PropertySize[];
  startingPrice: string;
  startingPriceNum: number;
  emergencyEligible: boolean;
  description: string;
  href: string;
  ctaText: "Get Instant Quote" | "Book This Service";
  badges?: string[];
  aliases: string[];
  imageSrc: string;
  popular?: boolean;
}

export const CATEGORY_DEFINITIONS: Record<ServiceCategory, { label: string; description: string }> = {
  cleaning: {
    label: "Cleaning",
    description: "End of tenancy, move-out, carpet extraction and deep appliance cleaning.",
  },
  "pest-control": {
    label: "Pest Control",
    description: "Certified treatments with written guarantees for rodents, insects and birds.",
  },
  gardening: {
    label: "Gardening",
    description: "2-gardener teams for maintenance, lawn mowing, clearances and green waste.",
  },
  removals: {
    label: "Removals",
    description: "House removals, Man & Van moving with Luton vans and full packing.",
  },
};

export const JOB_TYPE_DEFINITIONS: Record<JobType, { label: string; description: string }> = {
  "one-off": {
    label: "One-Off Service",
    description: "Single visit or scheduled appointment without long-term commitment.",
  },
  recurring: {
    label: "Recurring / Regular Service",
    description: "Scheduled ongoing visits (gardening maintenance, domestic cleaning, pest contracts).",
  },
  inspection: {
    label: "Inspection / Diagnostic Visit",
    description: "On-site assessment, pest survey, or drain camera diagnosis.",
  },
  emergency: {
    label: "Emergency / Same-Day Callout",
    description: "Rapid response slots for active infestations or urgent handovers.",
  },
};

export const PROPERTY_SIZE_DEFINITIONS: Record<PropertySize, { label: string; subtext: string }> = {
  studio: { label: "Studio", subtext: "Flat or Bedsit" },
  "1-bed": { label: "1 Bedroom", subtext: "Flat or Annex" },
  "2-bed": { label: "2 Bedroom", subtext: "Flat or Maisonette" },
  "3-bed": { label: "3 Bedroom", subtext: "House or Flat" },
  "4-plus": { label: "4+ Bedroom / House", subtext: "Large Family Home" },
  commercial: { label: "Commercial Property", subtext: "Office, Retail or Hospitality" },
};

export const SERVICES_DIRECTORY: DirectoryService[] = [
  // ==========================================
  // 1. CLEANING SERVICES
  // ==========================================
  {
    id: "end-of-tenancy-cleaning",
    name: "End of Tenancy Cleaning",
    category: "cleaning",
    categoryLabel: "Cleaning",
    subService: "End of Tenancy",
    jobTypes: ["one-off", "emergency"],
    propertySizes: ["studio", "1-bed", "2-bed", "3-bed", "4-plus"],
    startingPrice: "From £130",
    startingPriceNum: 130,
    emergencyEligible: true,
    description: "Agency-standard move out clean with 48-hour re-clean guarantee, covering full inventory checklists.",
    href: "/cleaning-services/end-of-tenancy-cleaning/",
    ctaText: "Get Instant Quote",
    badges: ["Guaranteed", "Most Booked"],
    aliases: ["tenancy", "move out", "deposit refund", "checkout clean", "flat clean", "deep clean", "landlord clean", "studio clean"],
    imageSrc: "/images/service/stock-hero-cleaning.jpg",
    popular: true,
  },
  {
    id: "domestic-regular-cleaning",
    name: "Regular Domestic Cleaning",
    category: "cleaning",
    categoryLabel: "Cleaning",
    subService: "Domestic Cleaning",
    jobTypes: ["recurring", "one-off"],
    propertySizes: ["studio", "1-bed", "2-bed", "3-bed", "4-plus"],
    startingPrice: "From £22/hr",
    startingPriceNum: 22,
    emergencyEligible: false,
    description: "Vetted weekly or fortnightly home cleaners for dusting, vacuuming, kitchen and bathroom upkeep.",
    href: "/cleaning-services/end-of-tenancy-cleaning/#calculator",
    ctaText: "Book This Service",
    badges: ["Flexible Schedule"],
    aliases: ["domestic", "regular", "maid", "housekeeping", "weekly clean", "fortnightly", "ironing"],
    imageSrc: "/images/service/stock-hero-cleaning.jpg",
    popular: true,
  },
  {
    id: "carpet-rug-cleaning",
    name: "Carpet & Rug Steam Cleaning",
    category: "cleaning",
    categoryLabel: "Cleaning",
    subService: "Carpet Cleaning",
    jobTypes: ["one-off", "recurring"],
    propertySizes: ["studio", "1-bed", "2-bed", "3-bed", "4-plus", "commercial"],
    startingPrice: "From £60",
    startingPriceNum: 60,
    emergencyEligible: false,
    description: "Hot water extraction removing deep-set dirt, pet odors and stubborn stains from carpets and rugs.",
    href: "/cleaning-services/carpet-cleaning/",
    ctaText: "Get Instant Quote",
    badges: ["Steam Extraction"],
    aliases: ["carpet", "rug", "steam clean", "stain removal", "hot water extraction", "upholstery refresh"],
    imageSrc: "/images/stock-handover-checklist.jpg",
    popular: true,
  },
  {
    id: "oven-appliance-cleaning",
    name: "Oven & Appliance Deep Cleaning",
    category: "cleaning",
    categoryLabel: "Cleaning",
    subService: "Oven Cleaning",
    jobTypes: ["one-off"],
    propertySizes: ["studio", "1-bed", "2-bed", "3-bed", "4-plus"],
    startingPrice: "From £45",
    startingPriceNum: 45,
    emergencyEligible: false,
    description: "Non-caustic dip-tank restoration removing baked-on carbon and grease from single, double and range ovens.",
    href: "/cleaning-services/oven-cleaning-service/",
    ctaText: "Book This Service",
    badges: ["Dip-Tank Degreasing"],
    aliases: ["oven clean", "cooker", "hob", "appliance", "range cooker", "extractor fan", "bbq"],
    imageSrc: "/images/stock-oven-kitchen.jpg",
    popular: true,
  },
  {
    id: "after-builders-cleaning",
    name: "After Builders Cleaning",
    category: "cleaning",
    categoryLabel: "Cleaning",
    subService: "Specialist Cleaning",
    jobTypes: ["one-off"],
    propertySizes: ["studio", "1-bed", "2-bed", "3-bed", "4-plus", "commercial"],
    startingPrice: "From £140",
    startingPriceNum: 140,
    emergencyEligible: false,
    description: "Fine dust extraction, paint and silicone residue removal following renovations and building work.",
    href: "/cleaning-services/after-builders-cleaning/",
    ctaText: "Get Instant Quote",
    badges: ["Post-Renovation"],
    aliases: ["builders clean", "renovation clean", "construction dust", "post works", "paint residue"],
    imageSrc: "/images/feature-property-services-green-v1.png",
  },
  {
    id: "window-cleaning",
    name: "Window & Glass Cleaning",
    category: "cleaning",
    categoryLabel: "Cleaning",
    subService: "Specialist Cleaning",
    jobTypes: ["one-off", "recurring"],
    propertySizes: ["studio", "1-bed", "2-bed", "3-bed", "4-plus", "commercial"],
    startingPrice: "From £40",
    startingPriceNum: 40,
    emergencyEligible: false,
    description: "Pure-water reach and wash pole system for streak-free external glass, frames, sills and internal panes.",
    href: "/cleaning-services/window-cleaning/",
    ctaText: "Book This Service",
    badges: ["Pure Water"],
    aliases: ["window", "glass", "reach and wash", "sills", "conservatory glass"],
    imageSrc: "/images/feature-property-handover-green-v1.png",
  },
  {
    id: "mattress-cleaning",
    name: "Mattress Steam Sanitising",
    category: "cleaning",
    categoryLabel: "Cleaning",
    subService: "Upholstery Cleaning",
    jobTypes: ["one-off"],
    propertySizes: ["studio", "1-bed", "2-bed", "3-bed", "4-plus"],
    startingPrice: "From £45",
    startingPriceNum: 45,
    emergencyEligible: false,
    description: "Deep high-pressure steam sanitisation targeting allergens, dust mites, sweat stains and odors.",
    href: "/cleaning-services/mattress-cleaning-service/",
    ctaText: "Book This Service",
    badges: ["Anti-Allergen"],
    aliases: ["mattress", "bed clean", "dust mites", "steam sanitise", "stain extraction"],
    imageSrc: "/images/feature-customer-guarantee-green-v1.png",
  },
  {
    id: "gutter-cleaning",
    name: "Gutter Clearance & Unblocking",
    category: "cleaning",
    categoryLabel: "Cleaning",
    subService: "Exterior Cleaning",
    jobTypes: ["one-off", "recurring"],
    propertySizes: ["1-bed", "2-bed", "3-bed", "4-plus", "commercial"],
    startingPrice: "From £60",
    startingPriceNum: 60,
    emergencyEligible: true,
    description: "High-reach wet vacuum gutter clearance removing moss, silt and autumn leaves up to 3 storeys high.",
    href: "/cleaning-services/gutter-cleaning/",
    ctaText: "Book This Service",
    badges: ["Vacuum Clearance"],
    aliases: ["gutter", "downpipe", "roofline", "moss", "blockage", "overflow"],
    imageSrc: "/images/feature-maintenance-plan-green-v1.png",
  },

  // ==========================================
  // 2. PEST CONTROL SERVICES
  // ==========================================
  {
    id: "mice-control",
    name: "Mice Control & Proofing",
    category: "pest-control",
    categoryLabel: "Pest Control",
    subService: "Rodent Control",
    jobTypes: ["one-off", "recurring", "inspection", "emergency"],
    startingPrice: "From £99",
    startingPriceNum: 99,
    emergencyEligible: true,
    description: "Targeted tamper-resistant bait stations, entry ingress surveys, and 1 to 3 month guarantee packages.",
    href: "/pest-control-services/mice-control/",
    ctaText: "Get Instant Quote",
    badges: ["Written Guarantee", "Emergency Available"],
    aliases: ["mice", "mouse", "rodent", "droppings", "scratching in walls", "vermin", "loft mice"],
    imageSrc: "/images/feature-team-arrival-green-v1.png",
    popular: true,
  },
  {
    id: "rat-control",
    name: "Rat Control & Sewer Investigation",
    category: "pest-control",
    categoryLabel: "Pest Control",
    subService: "Rodent Control",
    jobTypes: ["one-off", "recurring", "inspection", "emergency"],
    startingPrice: "From £109",
    startingPriceNum: 109,
    emergencyEligible: true,
    description: "Heavy rodent eradication plans, drain camera surveys, and full ingress blocking with written backing.",
    href: "/pest-control-services/rat-control/",
    ctaText: "Get Instant Quote",
    badges: ["Emergency Callout", "1-3 Mo Guarantee"],
    aliases: ["rat", "rats", "sewer rat", "garden rat", "drain check", "gnawing", "large rodent"],
    imageSrc: "/images/feature-team-arrival-green-v1.png",
    popular: true,
  },
  {
    id: "bed-bug-treatment",
    name: "Bed Bug Heat & Spray Treatment",
    category: "pest-control",
    categoryLabel: "Pest Control",
    subService: "Insect Eradication",
    jobTypes: ["one-off", "inspection", "emergency"],
    startingPrice: "From £149",
    startingPriceNum: 149,
    emergencyEligible: true,
    description: "Multi-stage residual insecticide and thermal heat eradication eliminating bugs, eggs, and nymphs.",
    href: "/pest-control-services/bed-bug-treatment/",
    ctaText: "Get Instant Quote",
    badges: ["Thermal + Chemical", "Discreet"],
    aliases: ["bedbug", "bed bugs", "bites", "blood spots", "mattress bugs", "heat treatment"],
    imageSrc: "/images/hero-property-services-green-v1.png",
    popular: true,
  },
  {
    id: "wasp-treatment",
    name: "Wasp Nest Removal & Eradication",
    category: "pest-control",
    categoryLabel: "Pest Control",
    subService: "Insect Eradication",
    jobTypes: ["one-off", "emergency"],
    startingPrice: "From £59",
    startingPriceNum: 59,
    emergencyEligible: true,
    description: "Rapid single-visit insecticide powder injection for eaves, lofts, sheds, and cavity wall nests.",
    href: "/pest-control-services/wasp-treatment/",
    ctaText: "Book This Service",
    badges: ["Same-Day Service", "Nest Neutralised"],
    aliases: ["wasp", "wasps", "wasp nest", "hornet", "stings", "loft wasp", "roofline nest"],
    imageSrc: "/images/feature-customer-guarantee-green-v1.png",
    popular: true,
  },
  {
    id: "cockroach-control",
    name: "Cockroach Eradication & Gel Baiting",
    category: "pest-control",
    categoryLabel: "Pest Control",
    subService: "Insect Eradication",
    jobTypes: ["one-off", "recurring", "inspection", "emergency"],
    startingPrice: "From £119",
    startingPriceNum: 119,
    emergencyEligible: true,
    description: "Commercial-grade gel baiting and insect growth regulators for German and Oriental cockroach infestations.",
    href: "/pest-control-services/cockroach-control/",
    ctaText: "Get Instant Quote",
    badges: ["Gel Baiting", "Commercial Grade"],
    aliases: ["cockroach", "roach", "german cockroach", "kitchen bugs", "night insects"],
    imageSrc: "/images/feature-property-services-green-v1.png",
  },
  {
    id: "flea-treatment",
    name: "Flea & Mite Insecticide Spraying",
    category: "pest-control",
    categoryLabel: "Pest Control",
    subService: "Insect Eradication",
    jobTypes: ["one-off", "emergency"],
    startingPrice: "From £89",
    startingPriceNum: 89,
    emergencyEligible: true,
    description: "Whole-property insect growth regulator misting to break the breeding cycle across carpets and upholstery.",
    href: "/pest-control-services/flea-treatment/",
    ctaText: "Book This Service",
    badges: ["Full Coverage"],
    aliases: ["flea", "fleas", "pet fleas", "carpet bites", "cat fleas", "dog fleas", "itching"],
    imageSrc: "/images/stock-handover-checklist.jpg",
  },
  {
    id: "ant-treatment",
    name: "Ant Treatment",
    category: "pest-control",
    categoryLabel: "Pest Control",
    subService: "Insect Eradication",
    jobTypes: ["one-off"],
    startingPrice: "From £69",
    startingPriceNum: 69,
    emergencyEligible: false,
    description: "Targeted treatment for ant trails and nests around kitchens, gardens and entry points.",
    href: "/pest-control-services/ant-treatment/",
    ctaText: "Book This Service",
    badges: [],
    aliases: ["ant", "ants", "ant nest", "ant trail"],
    imageSrc: "/images/stock-handover-checklist.jpg",
  },
  {
    id: "pest-inspection-survey",
    name: "Comprehensive Pest Inspection Survey",
    category: "pest-control",
    categoryLabel: "Pest Control",
    subService: "Diagnostics & Survey",
    jobTypes: ["inspection", "one-off"],
    startingPrice: "From £60",
    startingPriceNum: 60,
    emergencyEligible: false,
    description: "BPCA-certified property inspection identifying unknown pest signs, droppings, ingress routes and hazards.",
    href: "/pest-control-services/pest-inspection/",
    ctaText: "Book This Service",
    badges: ["Full Report"],
    aliases: ["pest inspection", "survey", "unknown droppings", "unidentified pest", "audit", "pre purchase survey"],
    imageSrc: "/images/feature-team-arrival-green-v1.png",
  },
  // "commercial-pest-contracts" removed 2026-09: commercial contracts aren't
  // launched yet and the old "From £49/mo" figure was a copy-paste of the
  // unrelated Best One Club subscription price, not a real commercial rate.
  // Re-add once a genuine starting price exists — the /pest-control-services/
  // commercial-pest-control/ page itself stays live with a "custom quote" cta.
  {
    id: "dead-pest-removal",
    name: "Dead Animal Removal & Sanitisation",
    category: "pest-control",
    categoryLabel: "Pest Control",
    subService: "Emergency Extraction",
    jobTypes: ["one-off", "emergency"],
    startingPrice: "From £80",
    startingPriceNum: 80,
    emergencyEligible: true,
    description: "Hygienic extraction of deceased rodents or birds from lofts, cavity walls and voids with biocidal deodorising.",
    href: "/pest-control-services/dead-pest-removal/",
    ctaText: "Book This Service",
    badges: ["Biocide Spray", "Same-Day"],
    aliases: ["dead animal", "dead rat", "dead fox", "smell in wall", "odour removal", "carcass removal"],
    imageSrc: "/images/feature-customer-guarantee-green-v1.png",
  },

  // ==========================================
  // 3. GARDENING SERVICES
  // ==========================================
  {
    id: "gardening-maintenance",
    name: "Garden Maintenance (2-Gardener Team)",
    category: "gardening",
    categoryLabel: "Gardening",
    subService: "General Maintenance",
    jobTypes: ["recurring", "one-off"],
    startingPrice: "From £70/1st hr",
    startingPriceNum: 70,
    emergencyEligible: false,
    description: "Two experienced gardeners with petrol mowers and strimmers for lawn edging, pruning, weeding and border care.",
    href: "/gardening/",
    ctaText: "Book This Service",
    badges: ["2-Man Team", "All Equipment"],
    aliases: ["gardener", "gardening", "lawn care", "mowing", "weeding", "pruning", "hedge trimming", "garden maintenance"],
    imageSrc: "/images/feature-property-services-green-v1.png",
    popular: true,
  },
  {
    id: "overgrown-garden-clearance",
    name: "Overgrown Garden Clearance & Green Waste",
    category: "gardening",
    categoryLabel: "Gardening",
    subService: "Garden Clearance",
    jobTypes: ["one-off", "emergency"],
    startingPrice: "From £120",
    startingPriceNum: 120,
    emergencyEligible: true,
    description: "Heavy jungle overgrowth cutting, bramble removal, ivy clearing, and licensed green waste disposal bags.",
    href: "/gardening/",
    ctaText: "Get Instant Quote",
    badges: ["Full Clearance", "Waste Included"],
    aliases: ["clearance", "overgrown", "jungle", "brambles", "ivy removal", "green waste", "tidy up", "waste removal"],
    imageSrc: "/images/feature-property-services-green-v1.png",
    popular: true,
  },
  {
    id: "hedge-trimming-shaping",
    name: "Hedge Trimming & Pruning",
    category: "gardening",
    categoryLabel: "Gardening",
    subService: "Hedge Care",
    jobTypes: ["one-off", "recurring"],
    startingPrice: "From £55",
    startingPriceNum: 55,
    emergencyEligible: false,
    description: "Precision boundary hedge cutting, height reduction, ornamental topiary, and shrub pruning.",
    href: "/gardening/",
    ctaText: "Book This Service",
    badges: ["Precision Trimming"],
    aliases: ["hedge", "hedges", "bush", "pruning", "conifers", "privet", "border cutting"],
    imageSrc: "/images/feature-maintenance-plan-green-v1.png",
  },
  {
    id: "lawn-mowing-turfing",
    name: "Lawn Mowing & Turf Laying",
    category: "gardening",
    categoryLabel: "Gardening",
    subService: "Lawn Care",
    jobTypes: ["one-off", "recurring"],
    startingPrice: "From £40",
    startingPriceNum: 40,
    emergencyEligible: false,
    description: "Strimmer edging, rotary mowing with clippings collection, aerating, and fresh cultivated turf laying.",
    href: "/gardening/",
    ctaText: "Book This Service",
    badges: ["Striped Finish"],
    aliases: ["lawn", "grass", "mowing", "turf", "turfing", "lawn care", "edging", "new lawn"],
    imageSrc: "/images/feature-verified-reviews-green-v1.png",
  },
  {
    id: "patio-pressure-washing",
    name: "Patio & Driveway Jet Washing",
    category: "gardening",
    categoryLabel: "Gardening",
    subService: "Jet Washing",
    jobTypes: ["one-off"],
    startingPrice: "From £85",
    startingPriceNum: 85,
    emergencyEligible: false,
    description: "Commercial high-PSI rotary pressure washing restoring stone flags, block paving, and garden decking.",
    href: "/gardening/",
    ctaText: "Get Instant Quote",
    badges: ["High PSI Restore"],
    aliases: ["jet wash", "pressure wash", "patio clean", "driveway clean", "moss removal", "decking clean", "flagstones"],
    imageSrc: "/images/service/stock-handover-checklist.jpg",
  },

  // ==========================================
  // 4. REMOVALS & WASTE SERVICES
  // ==========================================
  {
    id: "house-flat-removals",
    name: "House & Flat Removals (2 Men + Luton Van)",
    category: "removals",
    categoryLabel: "Removals",
    subService: "Home Removals",
    jobTypes: ["one-off"],
    propertySizes: ["1-bed", "2-bed", "3-bed", "4-plus"],
    startingPrice: "From £75/hr",
    startingPriceNum: 75,
    emergencyEligible: true,
    description: "Fully insured home moving crew with a Luton van equipped with tail lift, moving blankets and safety straps.",
    href: "/removals/",
    ctaText: "Get Instant Quote",
    badges: ["Goods in Transit Insured", "Tail Lift Luton"],
    aliases: ["removals", "moving house", "home move", "flat move", "luton van", "furniture move", "relocation", "packers"],
    imageSrc: "/images/feature-property-handover-green-v1.png",
    popular: true,
  },
  {
    id: "man-and-van-moving",
    name: "Man & Van Moving Services",
    category: "removals",
    categoryLabel: "Removals",
    subService: "Man & Van",
    jobTypes: ["one-off", "emergency"],
    propertySizes: ["studio", "1-bed", "2-bed"],
    startingPrice: "From £55/hr",
    startingPriceNum: 55,
    emergencyEligible: true,
    description: "Cost-effective small flat moves, single bulky item transport, and student relocations across Greater London.",
    href: "/removals/",
    ctaText: "Book This Service",
    badges: ["Hourly Rates", "Same-Day Slots"],
    aliases: ["man and van", "small move", "student move", "single item", "sofa collection", "ikea delivery", "cheap van"],
    imageSrc: "/images/feature-team-arrival-green-v1.png",
    popular: true,
  },
  {
    id: "packing-materials-service",
    name: "Professional Packing & Boxes",
    category: "removals",
    categoryLabel: "Removals",
    subService: "Packing Services",
    jobTypes: ["one-off"],
    propertySizes: ["1-bed", "2-bed", "3-bed", "4-plus", "commercial"],
    startingPrice: "From £25/hr",
    startingPriceNum: 25,
    emergencyEligible: false,
    description: "Professional fragile wrapping, double-walled packing boxes, bubble wrap and labeled room sorting.",
    href: "/removals/",
    ctaText: "Get Instant Quote",
    badges: ["Fragile Wrapping", "Boxes Provided"],
    aliases: ["packing", "moving boxes", "bubble wrap", "packing service", "unpacking", "fragile packing"],
    imageSrc: "/images/feature-property-handover-green-v1.png",
  },
  {
    id: "office-commercial-removals",
    name: "Office & Business Relocations",
    category: "removals",
    categoryLabel: "Removals",
    subService: "Commercial Moves",
    jobTypes: ["one-off"],
    propertySizes: ["commercial"],
    startingPrice: "From £150/hr",
    startingPriceNum: 150,
    emergencyEligible: false,
    description: "Out-of-hours office moves, desk dismantling, IT equipment handling and crate hire for London businesses.",
    href: "/removals/",
    ctaText: "Get Instant Quote",
    badges: ["Out of Hours", "Insured"],
    aliases: ["office move", "commercial removal", "business relocation", "desk move", "crate hire"],
    imageSrc: "/images/feature-property-services-green-v1.png",
  },
];
