import { NextResponse } from "next/server";
import { z } from "zod";
import { getFirebaseDb } from "@/lib/firebase-admin";
import { bookingStatuses } from "@/lib/booking";
import { statusTransitions } from "@/lib/booking-events";
import { requireRole } from "@/lib/roles";
const patchSchema = z.object({ status: z.enum(bookingStatuses).optional(), assignedStaffUid: z.string().max(128).nullable().optional(), internalNote: z.string().max(2000).optional() });
export async function GET(request: Request, { params }: { params: Promise<{ id: string }> }) { const actor = await requireRole(request, "admin"); if (!actor) return NextResponse.json({ error: "UNAUTHORIZED" }, { status: 401 }); const { id } = await params; const db = getFirebaseDb(); const [booking, events] = await Promise.all([db.collection("bookings").doc(id).get(), db.collection("bookingEvents").where("bookingId", "==", id).orderBy("createdAt").get()]); if (!booking.exists) return NextResponse.json({ error: "NOT_FOUND" }, { status: 404 }); return NextResponse.json({ id, ...booking.data(), events: events.docs.map((x) => x.data()) }); }
export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) { const actor = await requireRole(request, "admin"); if (!actor) return NextResponse.json({ error: "UNAUTHORIZED" }, { status: 401 }); const body = patchSchema.safeParse(await request.json()); if (!body.success) return NextResponse.json({ error: "INVALID_INPUT" }, { status: 400 }); const { id } = await params; const db = getFirebaseDb(); const ref = db.collection("bookings").doc(id); await db.runTransaction(async (tx) => { const current = await tx.get(ref); if (!current.exists) throw new Error("NOT_FOUND"); const before = current.data()!; if (body.data.status && !statusTransitions[before.status as keyof typeof statusTransitions].includes(body.data.status)) throw new Error("INVALID_TRANSITION"); tx.update(ref, { ...body.data, updatedAt: new Date() }); tx.set(db.collection("bookingEvents").doc(), { bookingId: id, type: body.data.status ? "status-change" : body.data.internalNote ? "internal-note" : "assignment", fromStatus: before.status, toStatus: body.data.status ?? before.status, actorUid: actor.uid, internalNote: body.data.internalNote ?? null, createdAt: new Date() }); }); return NextResponse.json({ ok: true }); }
