"use client";

import Link from "next/link";
import { useState } from "react";
import { GoogleAuthProvider, createUserWithEmailAndPassword, sendPasswordResetEmail, signInWithEmailAndPassword, signInWithPopup } from "firebase/auth";
import { getFirebaseClientAuth, isFirebaseClientConfigured } from "@/lib/firebase-client";

function GoogleMark() { return <svg viewBox="0 0 24 24" aria-hidden="true"><path fill="#4285F4" d="M21.8 12.2c0-.7-.1-1.4-.2-2H12v3.8h5.5a4.7 4.7 0 0 1-2 3.1v2.5h3.3c1.9-1.8 3-4.3 3-7.4Z"/><path fill="#34A853" d="M12 22c2.7 0 5-.9 6.7-2.4l-3.3-2.5c-.9.6-2 .9-3.4.9-2.6 0-4.9-1.8-5.7-4.2H3v2.6A10 10 0 0 0 12 22Z"/><path fill="#FBBC05" d="M6.3 13.8a6 6 0 0 1 0-3.6V7.6H3a10 10 0 0 0 0 8.8l3.3-2.6Z"/><path fill="#EA4335" d="M12 6c1.5 0 2.9.5 3.9 1.5l2.9-2.9A10 10 0 0 0 3 7.6l3.3 2.6C7.1 7.8 9.4 6 12 6Z"/></svg>; }
function AuthFrame({ children }: { children: React.ReactNode }) { return <main id="main-content" className="auth-page"><section className="auth-layout"><aside className="auth-visual"><div className="auth-visual-content"><p className="eyebrow">Customer account</p><h2>Everything for your property, in one place.</h2><p>Keep service requests, updates and your contact preferences together whenever you need them.</p><div className="auth-visual-note"><strong>Simple & secure</strong><span>Your account is optional. You can always request a service as a guest.</span></div></div></aside><section className="auth-panel">{children}</section></section></main>; }
function PasswordField({ value, onChange, label = "Password" }: { value: string; onChange: (value: string) => void; label?: string }) { const [show, setShow] = useState(false); return <label className="field password-field"><span>{label}</span><div><input value={value} type={show ? "text" : "password"} autoComplete={label === "Password" ? "current-password" : "new-password"} onChange={(event) => onChange(event.target.value)} /><button type="button" aria-label={show ? "Hide password" : "Show password"} onClick={() => setShow(!show)}><svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M2.5 12s3.4-5.5 9.5-5.5S21.5 12 21.5 12 18.1 17.5 12 17.5 2.5 12 2.5 12Z"/><circle cx="12" cy="12" r="2.5"/>{!show && <path d="M4 4 20 20"/>}</svg></button></div></label>; }
function AuthError({ message }: { message: string }) { return message ? <p className="auth-error" role="alert">{message}</p> : null; }
function configMessage() { return "Account sign-in is not configured on this deployment yet. Please add the Firebase environment variables in Vercel."; }
async function saveSession(idToken: string, next: string) { const response = await fetch("/api/auth/session", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ idToken }) }); if (!response.ok) throw new Error(response.status === 503 ? configMessage() : "We could not start your secure session. Please try again."); window.location.assign(next); }

export function LoginForm({ next }: { next: string }) { const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); async function submit(google = false) { if (!isFirebaseClientConfigured) return setError(configMessage()); if (!google && (!email || !password)) return setError("Enter your email address and password to sign in."); const auth = getFirebaseClientAuth(); if (!auth) return setError(configMessage()); setBusy(true); setError(""); try { const user = google ? (await signInWithPopup(auth, new GoogleAuthProvider())).user : (await signInWithEmailAndPassword(auth, email, password)).user; await saveSession(await user.getIdToken(), next); } catch (reason) { setError(reason instanceof Error ? reason.message : "Email or password is not correct. Please try again."); } finally { setBusy(false); } } return <AuthFrame><div className="auth-form-head"><h1>Sign in</h1><p>Use your email and password to continue.</p></div><AuthError message={error}/><label className="field"><span>Email</span><input value={email} type="email" autoComplete="email" placeholder="you@example.com" onChange={(event) => setEmail(event.target.value)} /></label><PasswordField value={password} onChange={setPassword}/><div className="auth-row"><Link href="/account/forgot-password/">Forgot password?</Link></div><button className="button auth-submit" disabled={busy} onClick={() => submit()}>{busy ? "Signing in…" : "Sign in"}</button><div className="auth-divider"><span>or continue with</span></div><button className="auth-google" disabled={busy} onClick={() => submit(true)}><GoogleMark/>Google</button><p className="auth-foot">No account? <Link href="/account/register/">Create one</Link></p></AuthFrame>; }

export function RegisterForm() { const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [terms, setTerms] = useState(false); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); async function submit() { if (!isFirebaseClientConfigured) return setError(configMessage()); if (!email || password.length < 6) return setError("Enter an email address and a password with at least 6 characters."); if (password !== confirm) return setError("Passwords do not match."); if (!terms) return setError("Please accept the Terms and Privacy Policy to create your account."); const auth = getFirebaseClientAuth(); if (!auth) return setError(configMessage()); setBusy(true); setError(""); try { const user = (await createUserWithEmailAndPassword(auth, email, password)).user; await saveSession(await user.getIdToken(), "/account/dashboard/"); } catch (reason) { setError(reason instanceof Error ? reason.message : "We could not create this account. Try a different email or a stronger password."); } finally { setBusy(false); } } async function google() { if (!isFirebaseClientConfigured) return setError(configMessage()); const auth = getFirebaseClientAuth(); if (!auth) return setError(configMessage()); setBusy(true); setError(""); try { const user = (await signInWithPopup(auth, new GoogleAuthProvider())).user; await saveSession(await user.getIdToken(), "/account/dashboard/"); } catch (reason) { setError(reason instanceof Error ? reason.message : "Google sign-in could not be completed."); } finally { setBusy(false); } } return <AuthFrame><div className="auth-form-head"><h1>Create account</h1></div><AuthError message={error}/><label className="field"><span>Email</span><input value={email} type="email" autoComplete="email" placeholder="you@example.com" onChange={(event) => setEmail(event.target.value)} /></label><PasswordField value={password} onChange={setPassword} label="Create password"/><PasswordField value={confirm} onChange={setConfirm} label="Confirm password"/><p className="auth-help">Use at least 6 characters.</p><label className="auth-terms"><input type="checkbox" checked={terms} onChange={(event) => setTerms(event.target.checked)}/><span>I agree to the <Link href="/terms-and-conditions/">Terms</Link> and <Link href="/privacy-policy/">Privacy Policy</Link>.</span></label><button className="button auth-submit" disabled={busy} onClick={submit}>{busy ? "Creating…" : "Create account"}</button><div className="auth-divider"><span>or continue with</span></div><button className="auth-google" disabled={busy} onClick={google}><GoogleMark/>Google</button><p className="auth-foot">Already have an account? <Link href="/account/login/">Sign in</Link></p></AuthFrame>; }

export function ResetForm() { const [email, setEmail] = useState(""); const [message, setMessage] = useState(""); async function submit() { if (!isFirebaseClientConfigured) return setMessage(configMessage()); if (!email) return setMessage("Enter your account email address."); const auth = getFirebaseClientAuth(); if (!auth) return setMessage(configMessage()); await sendPasswordResetEmail(auth, email); setMessage("If an account exists for this email, a reset link has been sent."); } return <AuthFrame><div className="auth-form-head"><h1>Reset password</h1><p>Enter your account email and we’ll send a reset link.</p></div><AuthError message={message}/><label className="field"><span>Email</span><input value={email} type="email" placeholder="you@example.com" onChange={(event) => setEmail(event.target.value)} /></label><button className="button auth-submit" onClick={submit}>Send reset link</button><p className="auth-foot"><Link href="/account/login/">Back to sign in</Link></p></AuthFrame>; }
