"use client";
import Link from "next/link";
import { useState } from "react";
import { GoogleAuthProvider, createUserWithEmailAndPassword, sendPasswordResetEmail, signInWithEmailAndPassword, signInWithPopup } from "firebase/auth";
import { getFirebaseClientAuth, isFirebaseClientConfigured } from "@/lib/firebase-client";

function AuthFrame({ children }: { children: React.ReactNode }) { return <main id="main-content" className="auth-page"><section className="auth-layout"><aside className="auth-visual"><div className="auth-visual-top"><span className="brand-mark">B1</span><strong>Best One Services</strong></div><div><p className="eyebrow">Customer account</p><h2>Everything for your property, in one place.</h2><p>Keep service requests, updates and your contact preferences together whenever you need them.</p></div><div className="auth-visual-note"><strong>Simple & secure</strong><span>Your account is optional. You can always request a service as a guest.</span></div></aside><section className="auth-panel">{children}</section></section></main>; }
function PasswordField({ value, onChange, label = "Password" }: { value: string; onChange: (value: string) => void; label?: string }) { const [show, setShow] = useState(false); return <label className="field password-field"><span>{label}</span><div><input value={value} type={show ? "text" : "password"} autoComplete={label === "Password" ? "current-password" : "new-password"} onChange={(e) => onChange(e.target.value)} /><button type="button" onClick={() => setShow(!show)}>{show ? "Hide" : "Show"}</button></div></label>; }
async function saveSession(idToken: string, next: string) { const r = await fetch("/api/auth/session", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ idToken }) }); if (!r.ok) throw new Error(); window.location.assign(next); }
export function LoginForm({ next }: { next: string }) { const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); async function submit(google = false) { const auth = getFirebaseClientAuth(); if (!auth) return setError("Sign-in is temporarily unavailable."); setBusy(true); setError(""); try { const user = google ? (await signInWithPopup(auth, new GoogleAuthProvider())).user : (await signInWithEmailAndPassword(auth, email, password)).user; await saveSession(await user.getIdToken(), next); } catch { setError("Email or password is not correct. Please try again."); } finally { setBusy(false); } } return <AuthFrame><div className="auth-form-head"><h1>Sign in</h1><p>Use your email and password to continue.</p></div>{error && <p className="auth-error" role="alert">{error}</p>}<label className="field"><span>Email</span><input value={email} type="email" autoComplete="email" placeholder="you@example.com" onChange={(e) => setEmail(e.target.value)} /></label><PasswordField value={password} onChange={setPassword} /><div className="auth-row"><Link href="/account/forgot-password/">Forgot password?</Link></div><button className="button auth-submit" disabled={busy || !email || !password || !isFirebaseClientConfigured} onClick={() => submit()}>{busy ? "Signing in…" : "Sign in"}</button><div className="auth-divider"><span>or continue with</span></div><button className="auth-google" disabled={busy || !isFirebaseClientConfigured} onClick={() => submit(true)}><span>G</span> Google</button><p className="auth-foot">No account? <Link href="/account/register/">Create one</Link></p></AuthFrame>; }
export function RegisterForm() { const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); async function submit() { const auth = getFirebaseClientAuth(); if (!auth) return setError("Account creation is temporarily unavailable."); setBusy(true); setError(""); try { const user = (await createUserWithEmailAndPassword(auth, email, password)).user; await saveSession(await user.getIdToken(), "/account/dashboard/"); } catch { setError("We could not create this account. Try a different email or a stronger password."); } finally { setBusy(false); } } return <AuthFrame><div className="auth-form-head"><h1>Create account</h1><p>Use one account to keep your future service requests together.</p></div>{error && <p className="auth-error" role="alert">{error}</p>}<label className="field"><span>Email</span><input value={email} type="email" autoComplete="email" placeholder="you@example.com" onChange={(e) => setEmail(e.target.value)} /></label><PasswordField value={password} onChange={setPassword} label="Create password" /><p className="auth-help">Use at least 6 characters.</p><button className="button auth-submit" disabled={busy || !email || password.length < 6 || !isFirebaseClientConfigured} onClick={submit}>{busy ? "Creating…" : "Create account"}</button><div className="auth-divider"><span>or continue with</span></div><button className="auth-google" disabled={busy || !isFirebaseClientConfigured} onClick={async () => { const auth = getFirebaseClientAuth(); if (!auth) return; const user = (await signInWithPopup(auth, new GoogleAuthProvider())).user; await saveSession(await user.getIdToken(), "/account/dashboard/"); }}><span>G</span> Google</button><p className="auth-foot">Already have an account? <Link href="/account/login/">Sign in</Link></p></AuthFrame>; }
export function ResetForm() { const [email, setEmail] = useState(""); const [message, setMessage] = useState(""); async function submit() { const auth = getFirebaseClientAuth(); if (!auth) return setMessage("Password reset is temporarily unavailable."); await sendPasswordResetEmail(auth, email); setMessage("If an account exists for this email, a reset link has been sent."); } return <AuthFrame><div className="auth-form-head"><h1>Reset password</h1><p>Enter your account email and we’ll send a reset link.</p></div>{message && <p className="auth-error">{message}</p>}<label className="field"><span>Email</span><input value={email} type="email" placeholder="you@example.com" onChange={(e) => setEmail(e.target.value)} /></label><button className="button auth-submit" disabled={!email || !isFirebaseClientConfigured} onClick={submit}>Send reset link</button><p className="auth-foot"><Link href="/account/login/">Back to sign in</Link></p></AuthFrame>; }
