"use client";
import Link from "next/link";
import { useState } from "react";
import { GoogleAuthProvider, signInWithEmailAndPassword, signInWithPopup } from "firebase/auth";
import { getFirebaseClientAuth, isFirebaseClientConfigured } from "@/lib/firebase-client";

export function LoginForm({ next }: { next: string }) {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function finish(idToken: string) { const r = await fetch("/api/auth/session", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ idToken }) }); if (!r.ok) throw new Error("Session could not be created."); window.location.assign(next); }
  async function login(provider: "password" | "google") { const auth = getFirebaseClientAuth(); if (!auth) return setError("Firebase sign-in is not configured in this environment."); setBusy(true); setError(""); try { const user = provider === "google" ? (await signInWithPopup(auth, new GoogleAuthProvider())).user : (await signInWithEmailAndPassword(auth, email, password)).user; await finish(await user.getIdToken()); } catch { setError("We could not sign you in. Check your details and try again."); } finally { setBusy(false); } }
  return <div className="auth-card"><div className="auth-brand"><span className="brand-mark">B1</span><span>Best One Services</span></div><p className="eyebrow">Customer account</p><h1>Welcome back</h1><p className="auth-copy">Sign in to view your service requests, updates and preferences.</p>{error && <p className="auth-error" role="alert">{error}</p>}<label className="field"><span>Email address</span><input value={email} type="email" autoComplete="email" onChange={(e) => setEmail(e.target.value)} /></label><label className="field"><span>Password</span><input value={password} type="password" autoComplete="current-password" onChange={(e) => setPassword(e.target.value)} /></label><div className="auth-row"><Link href="/account/forgot-password/">Forgot password?</Link></div><button className="button auth-submit" disabled={busy || !email || !password || !isFirebaseClientConfigured} onClick={() => login("password")}>{busy ? "Signing in…" : "Sign in"}</button><div className="auth-divider"><span>or</span></div><button className="button button-secondary auth-submit" disabled={busy || !isFirebaseClientConfigured} onClick={() => login("google")}>Continue with Google</button><p className="auth-foot">New here? <Link href="/account/register/">Create an account</Link></p></div>;
}
