import type { Metadata } from "next";
import Link from "next/link";
import { siteConfig } from "@/config/site";

const policies = {
  "privacy-policy": ["Privacy Policy", [["Who we are", "Bestone Services Ltd is the data controller for personal information collected during enquiries, bookings and service delivery. Company number: 15574809. Registered office: 28–42 Clements Road, Ilford, England, IG1 1BA."], ["How we collect and use information", "This website does not use online enquiry, booking or contact forms. If you call or email us, we may use contact, property, service, booking, payment and communication details to provide quotes, arrange services, process payments, meet legal obligations and deal with complaints."], ["Your rights", "Subject to applicable law, you may ask for access to, correction, erasure or restriction of personal information, object to certain processing, or withdraw consent. Email us to exercise your rights. You may also complain to the Information Commissioner’s Office."]]],
  "cookie-policy": ["Cookie Policy", [["How we use cookies", "Cookies are small files stored on your device. Strictly necessary cookies help the website work safely and effectively. Analytics and marketing cookies remain disabled unless you choose to accept them."], ["Managing cookies", "You can control cookies through browser settings. Blocking essential cookies may affect parts of the website. We will update this policy if third-party services or cookie providers change."]]],
  "terms-and-conditions": ["Terms and Conditions", [["Services and quotes", "Bestone Services Ltd provides end of tenancy cleaning and pest-control services across London. Starting prices are minimum prices for standard cases, not a binding quote. We confirm scope, availability and full price by telephone or email before a booking is finalised."], ["Customer responsibilities", "Customers must provide accurate property and service information, safe access, relevant hazards, preparation information and required permissions. Some pest treatments require multiple visits, monitoring, preparation or aftercare."], ["Cancellations and liability", "Consumer cancellation rights may apply under the Consumer Contracts Regulations 2013. Where work begins during a cancellation period, proportionate charges may apply. Nothing in these terms excludes liability where doing so would be unlawful."]]],
  "cancellation-and-refund-policy": ["Cancellation and Refund Policy", [["Cancelling or changing a booking", "Please call or email us as soon as possible with your name, property address, booking date and service booked. We will confirm receipt and explain the next step."], ["Consumer rights and refunds", "Eligible consumers may have a 14-day cancellation right. If you ask us to begin a service during that period, you may need to pay for work already provided. Refund eligibility depends on the agreed service, work completed and applicable law."], ["Service concerns", "If you are unhappy with a service, contact us promptly with the booking details and concerns so we can review the matter under our Complaints Policy."]]],
  "complaints-policy": ["Complaints Policy", [["Our commitment", "We aim to deal with complaints fairly, respectfully and as quickly as possible."], ["How to complain", "Call or email us with your name, service or booking details, property address, the concern and the outcome you would like us to consider."], ["What happens next", "We will acknowledge your complaint, review the available information and explain our response or any further steps. If your concern relates to personal information, you may also contact the Information Commissioner’s Office."]]],
  "accessibility-statement": ["Accessibility Statement", [["Our commitment", "Bestone Services Ltd aims to make this website usable for as many people as possible, including people using assistive technology, keyboard navigation or mobile devices."], ["Accessibility features", "The site uses semantic headings, keyboard focus states, a skip-to-content link, readable contrast and responsive layouts. We continue to improve the site as pages and services are added."], ["Contact us", "If you have difficulty using any part of this website or need information in another format, call or email us and tell us how we can help."]]],
} as const;

type PolicyKey = keyof typeof policies;
export function generateStaticParams() { return Object.keys(policies).map((policy) => ({ policy })); }
export async function generateMetadata({ params }: { params: Promise<{ policy: string }> }): Promise<Metadata> { const { policy } = await params; const item = policies[policy as PolicyKey]; return { title: item?.[0] ?? "Policy", alternates: { canonical: `/${policy}/` } }; }
export default async function PolicyPage({ params }: { params: Promise<{ policy: string }> }) { const { policy } = await params; const item = policies[policy as PolicyKey]; if (!item) return null; return <main id="main-content"><section className="section"><div className="shell reading legal-page"><p className="eyebrow">Bestone Services Ltd</p><h1>{item[0]}</h1><p className="lead">Last updated: [INSERT DATE]</p>{item[1].map(([heading, text]) => <section key={heading}><h2>{heading}</h2><p>{text}</p></section>)}<p>Contact: <a href={`mailto:${siteConfig.email}`}>{siteConfig.email}</a> · <a href={siteConfig.phoneHref}>{siteConfig.phone}</a></p><p><Link href="/">Back to home</Link></p></div></section></main>; }
